### ISSUE TITLE
IMAP connection working but no mail fetching

### ISSUE THREAD

**Issue by Lsm-CVX** [jonaswinkler/paperless-ng#1031]
Hi, 

I have installed and using this tremendous software for a few months now but I have a problem with the IMAP / Mail fetching. 

Paperless is installed on a docker via docker-compose and the email is hosted by IONOS (infos.com) but is attached to our company. 

Webmail access is checked 
 
The Paperless-NG configuration seems okay at least the reported : 

webserver_1  | 15:52:33 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
webserver_1  | 15:52:33 [Q] INFO Process-1:11 processing [carbon-bluebird-double-fruit]
webserver_1  | 15:52:33 [Q] INFO Process-1:11 stopped doing work
webserver_1  | 15:52:33 [Q] INFO Processed [carbon-bluebird-double-fruit]
webserver_1  | 15:52:33 [Q] INFO recycled worker Process-1:11
webserver_1  | 15:52:33 [Q] INFO Process-1:13 ready for work at 877

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/84283137/118404124-d40b4480-b671-11eb-8271-675949a2a2e5.png">

One email with attached PDF is sitting unread in the mailbox but nothing happened. 

I try to increase the verbosity of the mail_fetcher but no output came. I tried to change to SSL IMAP (also supported by IONOS and tested from our side) but it failed : 

SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091) : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/paperless_mail/tasks.py", line 15, in process_mail_accounts
account)
File "/usr/src/paperless/src/paperless_mail/mail.py", line 159, in handle_mail_account
account.imap_security) as M:
File "/usr/src/paperless/src/paperless_mail/mail.py", line 97, in get_mailbox
mailbox = MailBox(server, port)
File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 262, in __init__
super().__init__()
File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 28, in __init__
self.box = self._get_mailbox_client()
File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 277, in _get_mailbox_client
return imaplib.IMAP4_SSL(self._host, self._port, self._keyfile, self._certfile, self._ssl_context)
File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
IMAP4.__init__(self, host, port)
File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
self.open(host, port)
File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
IMAP4.open(self, host, port)
File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
self.sock = self._create_socket()
File "/usr/local/lib/python3.7/imaplib.py", line 1293, in _create_socket
server_hostname=self.host)
File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
session=session
File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
self.do_handshake()
File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

I  tried to localize the problem but the docker is missing quite a lot of tools (ping being one of the things I had in mind). Maybe you have some better idea to pinpoint the issue ? 

Thanks

Laurent

**Comment by Lsm-CVX** [comment]
I shall have added the logs from the software : 

[2021-05-16 16:12:08,624] [DEBUG] [paperless_mail] Processing mail account XXXXXXXX
[2021-05-16 16:12:08,915] [DEBUG] [paperless_mail] Account XXXXXXXX: Processing 1 rule(s)
[2021-05-16 16:12:08,917] [DEBUG] [paperless_mail] Rule XXXXXXXX.Inbox: Selecting folder Inbox
[2021-05-16 16:12:08,939] [DEBUG] [paperless_mail] Rule XXXXX.Inbox: Searching folder with criteria (SINCE 16-Apr-2021 FROM "*" SUBJECT "*" BODY "*" UNSEEN)
[2021-05-16 16:12:08,961] [DEBUG] [paperless_mail] RuleXXXXXXX.Inbox: Processed 0 matching mail(s)
[2021-05-16 16:12:08,962] [DEBUG] [paperless_mail] Rule XXXXXXX.fr.Inbox: Running mail actions on 0 mails

I tried as well to have a sub repository INBOX/Parperless (with the modification of the match rule) : 

[2021-05-16 16:23:11,596] [DEBUG] [paperless_mail] Processing mail account XXXXX
[2021-05-16 16:23:11,889] [DEBUG] [paperless_mail] Account XXXXXXX: Processing 1 rule(s)
[2021-05-16 16:23:11,895] [DEBUG] [paperless_mail] Rule XXXXXXX.Inbox Paperless: Selecting folder Paperless
[2021-05-16 16:23:11,917] [ERROR] [paperless_mail] Rule XXXXXX.Inbox Paperless: Error while processing rule: Rule XXXXXXX.Inbox Paperless: Folder Paperless does not exist in account XXXXXXXX
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 189, in handle_mail_rule
    M.folder.set(rule.folder)
  File "/usr/local/lib/python3.7/site-packages/imap_tools/folder.py", line 38, in set
    check_command_status(result, MailboxFolderSelectError)
  File "/usr/local/lib/python3.7/site-packages/imap_tools/utils.py", line 54, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxFolderSelectError: Response status "OK" expected, but "NO" received. Data: [b'unknown folder']
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 172, in handle_mail_account
    total_processed_files += self.handle_mail_rule(M, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 192, in handle_mail_rule
    f"Rule {rule}: Folder {rule.folder} "
paperless_mail.mail.MailError: Rule XXXXXX.Inbox Paperless: Folder Paperless does not exist in account XXXXXX

I am guessing that the INBOX is pretty okay but

**Comment by jonaswinkler** [comment]
Subfolders must be separated by dots, not slashes. I've already added a hint to the input fields (next version).

You can always install more tools with `apt`.

Which version are you using? 1.4.3 has updated dependencies that fix some issues with mail fetching.

**Comment by Lsm-CVX** [comment]
HI 

I am using the 1.4.3 version (upgraded today). No change for the problem but I found it ... it was my mistake : I had put jocker indication (*) on the senders, the subject and the text ....

I thought it was the same as the document filter (*.pdf)

Maybe a good idea to add this in the description ? 

Again thanks for your quick answer

**Comment by bym0** [comment]
> HI
> 
> I am using the 1.4.3 version (upgraded today). No change for the problem but I found it ... it was my mistake : I had put jocker indication (*) on the senders, the subject and the text ....
> 
> I thought it was the same as the document filter (*.pdf)
> 
> Maybe a good idea to add this in the description ?
> 
> Again thanks for your quick answer

Thank you! Was missing the same thing, plus i saw in the Logs i specified the wrong Charset for O365 Mailbox 

`[b'[BADCHARSET (US-ASCII)] The specified charset is not supported.']`
