### ISSUE TITLE
[BUG] Character set mail setting gives undefined column

### ISSUE THREAD

**Issue by alexpovel** [jonaswinkler/paperless-ng#1047]
**Describe the bug**

Updated from `1.4.3` to `1.4.4`. The [changelog for the latter](https://paperless-ng.readthedocs.io/en/latest/changelog.html#paperless-ng-1-4-4) states:

> Paperless mail: Added ability to specify the character set for each server.

I suspect it's this commit: https://github.com/jonaswinkler/paperless-ng/commit/870808f3c22f1a035fe9d8c0fff5af12ce404d4d .

**To Reproduce**
1. Have `1.4.3` (Docker)
2. Update to `1.4.4` (Docker)
3. Navigate to endpoint `/admin/paperless_mail/mailaccount/`
4. Observe server error 500

**Expected behavior**

For this to work like in 1.4.3, where mail worked.

**Webserver logs**
```
[2021-05-22 08:48:08,862] [ERROR] [django.request] Internal Server Error: /admin/paperless_mail/mailaccount/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column paperless_mail_mailaccount.character_set does not exist
LINE 1: ...ername", "paperless_mail_mailaccount"."password", "paperless...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 458, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 423, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 414, in wait_for
    return await fut
  File "/usr/local/lib/python3.7/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 462, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column paperless_mail_mailaccount.character_set does not exist
LINE 1: ...ername", "paperless_mail_mailaccount"."password", "paperless...
```

It gives `column paperless_mail_mailaccount.character_set does not exist` so we can pinpoint the problem. I don't know anything about databases, but would've thought this migration was taken care of here:

https://github.com/jonaswinkler/paperless-ng/blob/870808f3c22f1a035fe9d8c0fff5af12ce404d4d/src/paperless_mail/migrations/0008_auto_20210516_0940.py#L1-L28

I have tried going back to `1.4.3`, deleting my one existing SMTP account and starting from scratch in `1.4.4`. That didn't work, it seems this is a general issue in the DB, not with the settings in one specific account (I thought since that was an 'old' account it didn't have a character set specified, so that that would be the source of the error).

I have not yet tried wiping the installation and restoring from backup (all while running `1.4.4`). I was hoping there could be a less nuclear option.

**Relevant information**
 - Debian 10
 - Firefox
 - `1.4.4`
 - Docker

**Comment by jonaswinkler** [comment]
What database?

While Paperless is running, try

`docker-compose exec webserver python3 manage.py showmigrations`

Verify that all migrations are checked, and that paperless_mail -> 0008 exists.

If it exists and is not checked, try running

`docker-compose exec webserver python3 manage.py migrate`.

**Comment by alexpovel** [comment]
Oh sorry, this is with a `postgres` database.

Your answer nailed it. `0008` wasn't checked and `migrate` did the job. Thanks a ton!

**Comment by jonaswinkler** [comment]
I'm *really* curious why the migrations did not run at startup. The startup script should take care of that.

**Comment by alexpovel** [comment]
I looked at the relevant logs and found:

```
 Paperless-ng docker container starting...
 Creating directory /tmp/paperless
 Waiting for PostgreSQL to start...
 Apply database migrations...
 SystemCheckError: System check identified some issues:

 ERRORS:
 ?: PAPERLESS_CONSUMPTION_DIR is not writeable
         HINT: Set the permissions of
 drwxr-xr-x /usr/src/paperless/src/../consume
  to be writeable by the user running the Paperless services
 Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
 2021-05-21 14:12:39,621 INFO Set uid to user 0 succeeded
 2021-05-21 14:12:39,623 INFO supervisord started with pid 1
 2021-05-21 14:12:40,626 INFO spawned: 'consumer' with pid 33
 2021-05-21 14:12:40,628 INFO spawned: 'gunicorn' with pid 34
 2021-05-21 14:12:40,630 INFO spawned: 'scheduler' with pid 35
 [2021-05-21 14:12:40 +0200] [34] [INFO] Starting gunicorn 20.1.0
 [2021-05-21 14:12:40 +0200] [34] [INFO] Listening at: http://0.0.0.0:8000 (34)
 [2021-05-21 14:12:40 +0200] [34] [INFO] Using worker: paperless.workers.ConfigurableWorker
 [2021-05-21 14:12:40 +0200] [34] [INFO] Server is ready. Spawning workers
 SystemCheckError: System check identified some issues:

 ERRORS:
 ?: PAPERLESS_CONSUMPTION_DIR is not writeable
         HINT: Set the permissions of
 drwxr-xr-x /usr/src/paperless/src/../consume
  to be writeable by the user running the Paperless services
 SystemCheckError: System check identified some issues:

 ERRORS:
 ?: PAPERLESS_CONSUMPTION_DIR is not writeable
         HINT: Set the permissions of
 drwxr-xr-x /usr/src/paperless/src/../consume
  to be writeable by the user running the Paperless services
 2021-05-21 14:12:41,512 INFO exited: scheduler (exit status 1; not expected)
```

The consumption directory is an NFS mount, using Docker's native NFS driver. That keeps breaking and it seems every paperless-ng launch resets its permissions so I have to redo that each time (the directory also needs to be usable for an attached scanner, and NFS makes this an absolute nightmare). But all this is either NFS's limitations or my lack of understanding of NFS.

So it seems the migration directory requires the consumption directory to be writable and fails *entirely* if it isn't? From a first look, it seems like a database migration wouldn't need to care for that directory, so maybe it could be ignored here.

**Comment by jonaswinkler** [comment]
The system checks run with every django command, not just with the migrations. Checking folder permissions is one such check. Migrations might need to have permissions ensured, in case I need to modify or move data as part of a migration.

The motivation behind adjusting folder permissions is related to the `USERMAP_UID` and `USERMAP_GID` parameters. I need to make sure that the UID of user outside of docker who wants to write to the consume directory, the UID of all files inside the container, and the UID of the user running the web server / scheduler are all the same. Whenever these parameters change, I need to redo the permissions.

1.4.4 had a change that only adjusts the permissions once (usually on first run or when the above parameters change).

Just out of interest, what's the motivation for not having the container and volumes on the same machine?

**Comment by alexpovel** [comment]
>Just out of interest, what's the motivation for not having the container and volumes on the same machine?

Well, there's three machines:

1. Intel NUC as the main server, running all sorts of stuff, among them paperless-ng
2. a Synology NAS, at this point only for storage
3. the scanner

The NAS already comes with NFS, SMB exposed and running. The scanner logs into this via SMB and writes to the consumption directory. paperless-ng notices this and pulls in documents from the same directory, mounted as NFS.

The alternative would be to have the consumption directory on the NUC, aka the paperless-ng Docker host, and expose that (either NFS or SMB) to the network so the network scanner can write to it. That's possible but I like having storage centralized, aka anything that needs to be exposed via SMB/NFS lives on the NAS. Maybe the issue here is that the scanner is a *network* scanner (which is excellent). If it were a USB/local machine, it would be much simpler.

Let me know if this made sense to you. I'm not aware of anything that paperless-ng is doing wrong, NFS is just a nightmare in this sense (mapping user IDs properly without just granting R/W to everyone).
