### ISSUE TITLE
[BUG] Error during installation: "[Errno 28] No space left on device"

### ISSUE THREAD

**Issue by tsafen** [jonaswinkler/paperless-ng#1171]
**Description**
I'm unable to finish a fresh installation of the paperless-ng docker image (tika/SQlite version).

**To Reproduce**
1. Create paperless-ng folder
2. Download relevant .env and .yml files (SQLite version)
3. Run `docker-compose pull`
4. Run `docker-compose up -d`
5. The paperless_webserver_1 gives the following error in the logs: [Errno 28] (see log below)

**Webserver logs**

```
2021-07-15 13:12:46,619 INFO spawned: 'consumer' with pid 441
2021-07-15 13:12:47,620 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2021-07-15 13:12:48,691] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/src/../consume
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 171, in handle
    self.handle_inotify(directory, recursive)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 201, in handle_inotify
    descriptor = inotify.add_watch(directory, inotify_flags)
  File "/usr/local/lib/python3.7/site-packages/inotify_simple.py", line 110, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/usr/local/lib/python3.7/site-packages/inotify_simple.py", line 39, in _libc_call
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 28] No space left on device
2021-07-15 13:12:50,191 INFO exited: consumer (exit status 1; not expected)
```

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 20.04
 - Installation method: docker (/docker-compose)
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: changed the language of the default package, but this does not seem to influence the installation, it downloads the relevant language during the container spin-up.

**Comment by mweimerskirch** [comment]
What's the output of "df -i"?
It could be that you have lots of small files and no "inodes" left.
Inodes store information about your files and depending on your filesystem and on how it is configured, they might be used up.
If that's the case, it's not a bug in paperless-ng.

**Comment by SethDamiani** [comment]
I am experiencing the same issue as @tsafen. `df -i` shows less than 1% of inodes used.

**Comment by mweimerskirch** [comment]
After re-reading the stack trace in more detail, I noticed that it fails at "inotify.add_watch".
I remember seeing something similar on the original paperless project:
https://github.com/the-paperless-project/paperless/issues/370#issuecomment-399797429
The problem was a limit on the number of "watched" folders/files which had to be increased. Maybe the info from that thread helps.

**Comment by SethDamiani** [comment]
That worked for me! Thanks so much.

**Comment by fazzer4x** [comment]
I just experienced the same issue with no space left on device. Also increased inotify.add_watch and paperless started working.
