### ISSUE TITLE
[BUG] Paperless-ng no longer works on Synology DS218+ (DSM 7)

### ISSUE THREAD

**Issue by shiQzaL** [jonaswinkler/paperless-ng#1243]
Hello,
I running paperless-ng in docker on a Synology DS218+ with DSM 7. But now it no longer works.
I don't know when it stopped functioning. Maybe with upgrade from DSM 6 to 7 but I don't know.
I user docker-compose with latest image 1.4.5 from dockerhub. I have also already reinstalled paperless-ng but I get the same issues.
I don't know how I can get it working again.

**Docker / docker-compose version:**
Docker version 20.10.3, build b455053
docker-compose version 1.28.5, build 324b023a

**Used files:**

- .env
- docker-compose.env
- docker-compose.yml (sqlite)

**Issue:**
When I try to upload a PDF document via Webbrowser I get an error message: **HTTP-Fehler: 500 Internal Server Error**
Also the consume folder not works to upload documents.

**Docker Logs of paperless-ng container:**
_docker logs 'containerid'_
```
Paperless-ng docker container starting...
Mapping UID and GID for paperless:paperless to xxxx:xxxx (anonymized UID and GID)
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
2021-08-19 07:18:01,082 INFO Set uid to user 0 succeeded
2021-08-19 07:18:01,101 INFO supervisord started with pid 1
2021-08-19 07:18:02,104 INFO spawned: 'consumer' with pid 44
2021-08-19 07:18:02,108 INFO spawned: 'gunicorn' with pid 45
2021-08-19 07:18:02,117 INFO spawned: 'scheduler' with pid 46
2021-08-19 07:18:03,121 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-08-19 07:18:03,123 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-08-19 07:18:03,123 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2021-08-19 09:18:03 +0200] [45] [INFO] Starting gunicorn 20.1.0
[2021-08-19 09:18:03 +0200] [45] [INFO] Listening at: http://0.0.0.0:8000 (45)
[2021-08-19 09:18:03 +0200] [45] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2021-08-19 09:18:03 +0200] [45] [INFO] Server is ready. Spawning workers
09:18:05 [Q] INFO Q Cluster victor-pip-sad-johnny starting.
[2021-08-19 09:18:05,784] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/src/../consume
[2021-08-19 09:20:04 +0200] [45] [CRITICAL] WORKER TIMEOUT (pid:55)
[2021-08-19 09:20:04 +0200] [45] [WARNING] Worker with pid 55 was terminated due to signal 6
09:20:12 [Q] ERROR Can not connect to Redis server.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 168, in __init__
    self.start()
  File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 171, in start
    self.broker.ping()
  File "/usr/local/lib/python3.7/site-packages/django_q/brokers/redis_broker.py", line 39, in ping
    raise e
  File "/usr/local/lib/python3.7/site-packages/django_q/brokers/redis_broker.py", line 36, in ping
    return self.connection.ping()
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to broker:6379. Connection timed out.
[2021-08-19 09:27:41,787] [WARNING] [django.request] Not Found: /api/logs/mail/
[2021-08-19 09:27:44,341] [WARNING] [django.request] Not Found: /api/logs/mail/
```

Thanks for your help!

**Comment by heikomat** [comment]
> Can not connect to Redis server

More like: Redis is not running.
Make sure the redis your paperless installation is using is running and available

**Comment by shiQzaL** [comment]
> > Can not connect to Redis server
> 
> Make sure the redis your paperless installation is using is running and available

Thank you for reply. 
The Redis Server was automatically installed with the docker-compose.yml file. In Synology Docker GUI I can see that the Redis Container is running. 
How can I check that it is available for paperless-ng?

Thank you.

**Comment by Fernando-Checa** [comment]
I had to open these ports on the firewall
5432,6379,9998

**Comment by shiQzaL** [comment]
> I had to open these ports on the firewall
> 5432,6379,9998

You are right. I just allow some internal IP subnets in my Synology Firewall and deny all others IP's accessing the Synology. With allowing Docker default IP-Range 172.17.0.0/16 it works again.

Thank you for this hint.
