### ISSUE TITLE
[BUG] PermissionError: [Errno 1] Operation not permitted / AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'

### ISSUE THREAD

**Issue by melihcoban** [jonaswinkler/paperless-ng#1251]
**Describe the bug**
Fresh install of paperless-ng using docker-compose gives several errors in the logs, I can access the site (username/password login) but cannot docker-compose run --rm webserver createsuperuser as it ends with an error.

**To Reproduce**
1. Use the docker-compose.yml and docker-compose.env in the repository inside the paperless folder.
2. Run docker-compose up -d (tried docker-compose up -d --build does not effect anything)
3. You can see the errors with docker-compose logs -f followup)

**Expected behavior**
I expected to get no errors whatsoever, and wanted to create a superuser to login to the site.

**Screenshots**

**Webserver logs (Installation)**

(I have no idea why it added 33m/36m while logging, in my end it is shown as webserver_1 etc)
https://gist.github.com/melihcoban/8917d1888c4635f53dc7fec7d3cf09c8

```
Attaching to paperless_webserver_1, paperless_broker_1
[36mbroker_1     |[0m 1:C 23 Aug 2021 21:01:17.701 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[36mbroker_1     |[0m 1:C 23 Aug 2021 21:01:17.701 # Redis version=6.0.15, bits=32, commit=00000000, modified=0, pid=1, just started
[36mbroker_1     |[0m 1:C 23 Aug 2021 21:01:17.701 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[36mbroker_1     |[0m 1:M 23 Aug 2021 21:01:17.707 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
[36mbroker_1     |[0m 1:M 23 Aug 2021 21:01:17.708 * Running mode=standalone, port=6379.
[36mbroker_1     |[0m 1:M 23 Aug 2021 21:01:17.708 # Server initialized
[36mbroker_1     |[0m 1:M 23 Aug 2021 21:01:17.708 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[36mbroker_1     |[0m 1:M 23 Aug 2021 21:01:17.709 * Ready to accept connections
[33mwebserver_1  |[0m Paperless-ng docker container starting...
[33mwebserver_1  |[0m Creating directory /tmp/paperless
[33mwebserver_1  |[0m Adjusting permissions of paperless files. This may take a while.
[33mwebserver_1  |[0m Apply database migrations...
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
[33mwebserver_1  |[0m     self.execute(*args, **cmd_options)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
[33mwebserver_1  |[0m     output = self.handle(*args, **options)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
[33mwebserver_1  |[0m     res = handle_func(*args, **kwargs)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
[33mwebserver_1  |[0m     self.check(databases=[database])
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
[33mwebserver_1  |[0m     all_issues = checks.run_checks(
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
[33mwebserver_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[33mwebserver_1  |[0m   File "/usr/src/paperless/src/documents/checks.py", line 18, in changed_password_check
[33mwebserver_1  |[0m     encrypted_doc = Document.objects.filter(
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
[33mwebserver_1  |[0m     for obj in (self if self.ordered else self.order_by('pk'))[:1]:
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
[33mwebserver_1  |[0m     self._fetch_all()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
[33mwebserver_1  |[0m     self._result_cache = list(self._iterable_class(self))
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
[33mwebserver_1  |[0m     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
[33mwebserver_1  |[0m     cursor = self.connection.cursor()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
[33mwebserver_1  |[0m     event_loop = asyncio.get_event_loop()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
[33mwebserver_1  |[0m     self.set_event_loop(self.new_event_loop())
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
[33mwebserver_1  |[0m     return self._loop_factory()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
[33mwebserver_1  |[0m     super().__init__(selector)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
[33mwebserver_1  |[0m     super().__init__()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
[33mwebserver_1  |[0m     self._clock_resolution = time.get_clock_info('monotonic').resolution
[33mwebserver_1  |[0m PermissionError: [Errno 1] Operation not permitted
[33mwebserver_1  |[0m 
[33mwebserver_1  |[0m During handling of the above exception, another exception occurred:
[33mwebserver_1  |[0m 
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/src/paperless/src/manage.py", line 11, in <module>
[33mwebserver_1  |[0m     execute_from_command_line(sys.argv)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
[33mwebserver_1  |[0m     utility.execute()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
[33mwebserver_1  |[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 367, in run_from_argv
[33mwebserver_1  |[0m     connections.close_all()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 213, in close_all
[33mwebserver_1  |[0m     connection.close()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
[33mwebserver_1  |[0m     event_loop = asyncio.get_event_loop()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
[33mwebserver_1  |[0m     self.set_event_loop(self.new_event_loop())
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
[33mwebserver_1  |[0m     return self._loop_factory()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
[33mwebserver_1  |[0m     super().__init__(selector)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
[33mwebserver_1  |[0m     super().__init__()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
[33mwebserver_1  |[0m     self._clock_resolution = time.get_clock_info('monotonic').resolution
[33mwebserver_1  |[0m PermissionError: [Errno 1] Operation not permitted
[33mwebserver_1  |[0m Exception ignored in: <function BaseEventLoop.__del__ at 0x76406a48>
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__
[33mwebserver_1  |[0m     _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
[33mwebserver_1  |[0m     f'closed={self.is_closed()} debug={self.get_debug()}>'
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
[33mwebserver_1  |[0m     return self._debug
[33mwebserver_1  |[0m AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
[33mwebserver_1  |[0m Exception ignored in: <function BaseEventLoop.__del__ at 0x76406a48>
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__
[33mwebserver_1  |[0m     _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
[33mwebserver_1  |[0m     f'closed={self.is_closed()} debug={self.get_debug()}>'
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
[33mwebserver_1  |[0m     return self._debug
[33mwebserver_1  |[0m AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
[33mwebserver_1  |[0m Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
[33mwebserver_1  |[0m 2021-08-23 21:01:26,662 INFO Set uid to user 0 succeeded
[33mwebserver_1  |[0m 2021-08-23 21:01:26,672 INFO supervisord started with pid 1
[33mwebserver_1  |[0m 2021-08-23 21:01:27,682 INFO spawned: 'consumer' with pid 27
[33mwebserver_1  |[0m 2021-08-23 21:01:27,695 INFO spawned: 'gunicorn' with pid 28
[33mwebserver_1  |[0m 2021-08-23 21:01:27,708 INFO spawned: 'scheduler' with pid 29
[33mwebserver_1  |[0m 2021-08-23 21:01:28,713 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[33mwebserver_1  |[0m 2021-08-23 21:01:28,715 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[33mwebserver_1  |[0m 2021-08-23 21:01:28,716 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[33mwebserver_1  |[0m [2021-08-24 00:01:29 +0300] [28] [INFO] Starting gunicorn 20.1.0
[33mwebserver_1  |[0m [2021-08-24 00:01:29 +0300] [28] [INFO] Listening at: http://0.0.0.0:8000 (28)
[33mwebserver_1  |[0m [2021-08-24 00:01:29 +0300] [28] [INFO] Using worker: paperless.workers.ConfigurableWorker
[33mwebserver_1  |[0m [2021-08-24 00:01:29 +0300] [28] [INFO] Server is ready. Spawning workers
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
[33mwebserver_1  |[0m     self.execute(*args, **cmd_options)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 393, in execute
[33mwebserver_1  |[0m     self.check()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
[33mwebserver_1  |[0m     all_issues = checks.run_checks(
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
[33mwebserver_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[33mwebserver_1  |[0m   File "/usr/src/paperless/src/documents/checks.py", line 18, in changed_password_check
[33mwebserver_1  |[0m     encrypted_doc = Document.objects.filter(
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
[33mwebserver_1  |[0m     for obj in (self if self.ordered else self.order_by('pk'))[:1]:
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
[33mwebserver_1  |[0m     self._fetch_all()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
[33mwebserver_1  |[0m     self._result_cache = list(self._iterable_class(self))
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
[33mwebserver_1  |[0m     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
[33mwebserver_1  |[0m     cursor = self.connection.cursor()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
[33mwebserver_1  |[0m     event_loop = asyncio.get_event_loop()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
[33mwebserver_1  |[0m     self.set_event_loop(self.new_event_loop())
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
[33mwebserver_1  |[0m     return self._loop_factory()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
[33mwebserver_1  |[0m     super().__init__(selector)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
[33mwebserver_1  |[0m     super().__init__()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
[33mwebserver_1  |[0m     self._clock_resolution = time.get_clock_info('monotonic').resolution
[33mwebserver_1  |[0m PermissionError: [Errno 1] Operation not permitted
[33mwebserver_1  |[0m 
[33mwebserver_1  |[0m During handling of the above exception, another exception occurred:
[33mwebserver_1  |[0m 
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/src/paperless/src/manage.py", line 11, in <module>
[33mwebserver_1  |[0m     execute_from_command_line(sys.argv)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
[33mwebserver_1  |[0m     utility.execute()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
[33mwebserver_1  |[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 367, in run_from_argv
[33mwebserver_1  |[0m     connections.close_all()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 213, in close_all
[33mwebserver_1  |[0m     connection.close()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
[33mwebserver_1  |[0m     event_loop = asyncio.get_event_loop()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
[33mwebserver_1  |[0m     self.set_event_loop(self.new_event_loop())
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
[33mwebserver_1  |[0m     return self._loop_factory()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
[33mwebserver_1  |[0m     super().__init__(selector)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
[33mwebserver_1  |[0m     super().__init__()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
[33mwebserver_1  |[0m     self._clock_resolution = time.get_clock_info('monotonic').resolution
[33mwebserver_1  |[0m PermissionError: [Errno 1] Operation not permitted
[33mwebserver_1  |[0m Exception ignored in: <function BaseEventLoop.__del__ at 0x763e0a90>
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__
[33mwebserver_1  |[0m     _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
[33mwebserver_1  |[0m     f'closed={self.is_closed()} debug={self.get_debug()}>'
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
[33mwebserver_1  |[0m     return self._debug
[33mwebserver_1  |[0m AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
[33mwebserver_1  |[0m Exception ignored in: <function BaseEventLoop.__del__ at 0x763e0a90>
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__
[33mwebserver_1  |[0m     _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
[33mwebserver_1  |[0m     f'closed={self.is_closed()} debug={self.get_debug()}>'
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
[33mwebserver_1  |[0m     return self._debug
[33mwebserver_1  |[0m AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
[33mwebserver_1  |[0m Traceback (most recent call last):
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
[33mwebserver_1  |[0m     self.execute(*args, **cmd_options)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 393, in execute
[33mwebserver_1  |[0m     self.check()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
[33mwebserver_1  |[0m     all_issues = checks.run_checks(
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
[33mwebserver_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[33mwebserver_1  |[0m   File "/usr/src/paperless/src/documents/checks.py", line 18, in changed_password_check
[33mwebserver_1  |[0m     encrypted_doc = Document.objects.filter(
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
[33mwebserver_1  |[0m     for obj in (self if self.ordered else self.order_by('pk'))[:1]:
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
[33mwebserver_1  |[0m     self._fetch_all()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
[33mwebserver_1  |[0m     self._result_cache = list(self._iterable_class(self))
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
[33mwebserver_1  |[0m     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
[33mwebserver_1  |[0m     cursor = self.connection.cursor()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
[33mwebserver_1  |[0m     event_loop = asyncio.get_event_loop()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
[33mwebserver_1  |[0m     self.set_event_loop(self.new_event_loop())
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
[33mwebserver_1  |[0m     return self._loop_factory()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
[33mwebserver_1  |[0m     super().__init__(selector)
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
[33mwebserver_1  |[0m     super().__init__()
[33mwebserver_1  |[0m   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
[33mwebserver_1  |[0m     self._clock_resolution = time.get_clock_info('monotonic').resolution
[33mwebserver_1  |[0m PermissionError: [Errno 1] Operation not permitted
```

**Webserver logs (createsuperuser)**

```
Executing management command createsuperuser
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/src/paperless/src/documents/checks.py", line 18, in changed_password_check
    encrypted_doc = Document.objects.filter(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
    event_loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
    super().__init__()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 213, in close_all
    connection.close()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
    event_loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
    super().__init__()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <function BaseEventLoop.__del__ at 0x76327a48>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
    f'closed={self.is_closed()} debug={self.get_debug()}>'
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
Exception ignored in: <function BaseEventLoop.__del__ at 0x76327a48>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
    f'closed={self.is_closed()} debug={self.get_debug()}>'
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
ERROR: 1
```

**Relevant information**
 - Host OS of the machine running paperless: [Raspberry Pi 3b+ 5.10.52-v7+ BST 2021 armv7l GNU/Linux]
 - Browser [Chrome]
 - Version [Latest]
 - Installation method: [Docker with docker-compose]
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
 Added required traefik network and labels to docker-compose.yml, other than that no changes.

```
    networks:
    - proxy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.paperless.rule=Host(`paperless.xxxxxx.local`)"
        - "traefik.http.routers.paperless.tls=true"
        - "traefik.http.services.paperless.loadbalancer.server.port=8000"
         
networks:
      proxy:
          external: true 
```

**Comment by melihcoban** [comment]
Raspberry have the old version of libseccomp2 (2.3.3-4) in its repositories. Running the following command fixes the issue. For the time being it would be useful to add this as an warning to documentation under `On Raspberry Pi, these libraries are required as well:
`
```
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```

**Comment by fantasticle** [comment]
> Raspberry have the old version of libseccomp2 (2.3.3-4) in its repositories. Running the following command fixes the issue. For the time being it would be useful to add this as an warning to documentation under `On Raspberry Pi, these libraries are required as well: `
> 
> ```
> wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
> sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
> ```

Works like a charm. Thank you.

**Comment by melihcoban** [comment]
> I still get the exact same error message, despite having applied the fix from @melihcoban's post. (While installing paperless-ng with the docker script)
> 
> Raspberry Pi 2 Model B
> Linux raspi02 5.10.52-v7+ #1441 SMP Tue Aug 3 18:10:09 BST 2021 armv7l GNU/Linux
> Raspbian Buster (v10.10)

This might be a long shot but what is your Python version? Latest changelog says that support for Python 3.6 is dropped and docker image is using python 3.9 . As far as I know Raspberry has Python 3.7 in its repositories so maybe updating the Python to latest version will fix the issue for you.

**Comment by KenADev** [comment]
@melihcoban: 
I am running Python 3.7.3, but I don't want to go through the hassle of upgrading Python from source right now. 
However, I found that setting  "privleged: true" under webservice in the docker-compose.yml solves the issue, even though that's probably not the most secure option of doing so.

@fantasticle: You wrote you installed it on a new Raspberry Pi?
Whats your Python version?

**Comment by fantasticle** [comment]
> @fantasticle: You wrote you installed it on a new Raspberry Pi?
> Whats your Python version?

@KenADev Python 3.8.10 came right out of the box with the newest Raspbian install
