### ISSUE TITLE
[BUG] [ERROR] [paperless.consumer] Error while consuming document file.png: UnsupportedImageFormatError:

### ISSUE THREAD

**Issue by llitz** [jonaswinkler/paperless-ng#1254]
When trying to process most of my png files the consumer fails.
Converting the exact same image to jpg make the scan work.

This is being tested with the docker version of paperless-ng.

Relevant logs:

```
[2021-08-24 17:27:33,830] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/ss-2021-08-24-172728.png to the task queue.
[2021-08-24 17:27:33,885] [INFO] [paperless.consumer] Consuming ss-2021-08-24-172728.png
[2021-08-24 17:27:33,886] [DEBUG] [paperless.consumer] Detected mime type: image/png
[2021-08-24 17:27:33,891] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2021-08-24 17:27:33,893] [DEBUG] [paperless.consumer] Parsing ss-2021-08-24-172728.png...
[2021-08-24 17:27:34,020] [WARNING] [paperless.parsing.tesseract] Error while getting DPI from image /usr/src/paperless/src/../consume/ss-2021-08-24-172728.png: 'dpi'
[2021-08-24 17:27:34,020] [DEBUG] [paperless.parsing.tesseract] Estimated DPI 175 based on image width 1453
[2021-08-24 17:27:34,021] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/ss-2021-08-24-172728.png', 'output_file': '/tmp/paperless/paperless-rfj0v800/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-rfj0v800/sidecar.txt', 'image_dpi': 175}
[2021-08-24 17:27:34,186] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-rfj0v800
[2021-08-24 17:27:34,189] [ERROR] [paperless.consumer] Error while consuming document ss-2021-08-24-172728.png: UnsupportedImageFormatError:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 354, in run_pipeline
    origin_pdf = triage(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 143, in triage
    triage_image_file(input_file, output_file, options)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 82, in triage_image_file
    raise UnsupportedImageFormatError()
ocrmypdf.exceptions.UnsupportedImageFormatError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: UnsupportedImageFormatError:
```

The sample images are not relevant from a data perspective, but this happens with any of my files, I constantly take screenshots in png format and store them. Trying out paperless-ng it failed on almost all of my images.

failed png
![failed png](https://user-images.githubusercontent.com/22463547/130703243-c0cdf05d-1f50-4bfc-832b-fd74df1d42ae.png)

working jpg
![working jpg](https://user-images.githubusercontent.com/22463547/130703221-6d3b904f-88be-4815-bdfd-7eee8dd82bdd.jpg)

**Comment by stepanov1975** [comment]
Have some problem with PNG files created by windows snipping tool

**Comment by jhqv** [comment]
> I also have thoose troubles with PNGs that come from a screenshot utility (LightScreen).

If you meant to say LightShot (a Mac screenshot app), then I might have experienced the same issue. I just started adding recipes to my Paperless instance, and the attached recipe (which was probably captured using Lightshot) can't be imported.

![Sthlm Mitt i adana spett](https://user-images.githubusercontent.com/8491785/134930234-1ead8ae3-2d6d-4953-9535-6ad711ce47b7.png)

**Comment by JosephCW** [comment]
I too encounter this problem when using any screenshots taken in Linux with the GNOME screenshot tool.

![screenshot](https://user-images.githubusercontent.com/4164889/141702148-6d0b16f4-4b42-46f2-94fd-73da1dfd94e0.png)

**Comment by JosephCW** [comment]
I was able to identify what our culprit was.

I'm in the process of setting up a development environment for paperless-ng and while I'm having some issues I'd like to take a stab at forwarding the full error to the logs a bit later... (Don't let this deter anyone else from doing it first :smile: )

**If the image still has an alpha channel on it then the library used by paperless-ng, ocrmypdf, throws an error stating that the input image has an alpha channel and suggests removing it.**

This is the output when trying to manually run ocrmypdf against the failed and working .png files provided by @llitz .
```
joseph@swirl:~$ ocrmypdf --image-dpi 80 failed.png output.pdf
Input file is not a PDF, checking if it is an image...
Input file is an image
The input image has an alpha channel. Remove the alpha channel first.
UnsupportedImageFormatError

joseph@swirl:~$ ocrmypdf --image-dpi 80 working.png output.pdf
Input file is not a PDF, checking if it is an image...
Input file is an image
Input image has no ICC profile, assuming sRGB
Image seems valid. Try converting to PDF...
Successfully converted to PDF, processing...
Scanning contents: 100%|███████████████████████| 1/1 [00:00<00:00, 360.18page/s]
Using Tesseract OpenMP thread limit 3
OCR: 100%|██████████████████████████████████| 1.0/1.0 [00:00<00:00,  2.07page/s]
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.00 savings: 0.0%
Output file is a PDF/A-2B (as expected)
```

I verified this by removing the alpha layer in my previous screenshot in GIMP by going to Layer -> Transparency -> Remove Alpha Channel. This is the file at ~/Pictures/screenshot.png. The original file is at ~/screenshot.png.

```
joseph@swirl:~$ ocrmypdf --image-dpi 80 Pictures/screenshot.png output.pdf
Input file is not a PDF, checking if it is an image...
Input file is an image
The input image has an alpha channel. Remove the alpha channel first.
UnsupportedImageFormatError

joseph@swirl:~$ ocrmypdf --image-dpi 80 screenshot.png output.pdf
Input file is not a PDF, checking if it is an image...
Input file is an image
Input image has no ICC profile, assuming sRGB
Image seems valid. Try converting to PDF...
Successfully converted to PDF, processing...
Scanning contents: 100%|███████████████████████| 1/1 [00:00<00:00, 360.49page/s]
Using Tesseract OpenMP thread limit 3
    1 [tesseract] Empty page!!                                                  
    1 [tesseract] Empty page!!                                                  
OCR: 100%|██████████████████████████████████| 1.0/1.0 [00:00<00:00,  2.21page/s]
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.00 savings: 0.0%
Output file is a PDF/A-2B (as expected)
```

**Comment by jhqv** [comment]
Excellent find, @JosephCW!

**Comment by Pheggas** [comment]
Thank you @JosephCW ! Also for the devs, could someone fix this bug? or make pull request?
