### ISSUE TITLE
This writer is closed

### ISSUE THREAD

**Issue by unintended-consequences** [jonaswinkler/paperless-ng#1346]
I can only seem to add one document to the database. 
Upon adding a second document, the dashboard gives: 
> This writer is closed

Logs have this output:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 288, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 296, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 388, in add_to_index
    index.add_or_update_document(document)
  File "/usr/src/paperless/src/documents/index.py", line 140, in add_or_update_document
    update_document(writer, document)
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/src/paperless/src/documents/index.py", line 94, in open_index_writer
    writer.commit(optimize=optimize)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 1037, in commit
    self.writer.commit(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 920, in commit
    self._check_state()
  File "/usr/local/lib/python3.9/site-packages/whoosh/writing.py", line 555, in _check_state
    raise IndexingError("This writer is closed")
whoosh.writing.IndexingError: This writer is closed`

**Comment by MertSafter** [comment]
Same issue here

**Comment by unintended-consequences** [comment]
I never resolved it. Has to give up. Happy to try again if you have any
ideas?

**Comment by MertSafter** [comment]
Hi,
I am using paperless within a docker container and managed to fix this issue, by deleting all folders I've mounted and the paperless docker image and did a fresh installation of the image. After that I so far don't get the issue anymore. 

Of course I did a backup of the original uploaded files in the media/documents/original folder. And after the clean install I moved all the backuped files to the consume folder and all (30 documents) were processed without issues.

**Comment by vincent** [comment]
Hi,
Same issue here.
Tried to switch between Postgre and SQLite, no differences.

I was wondering if some of you also use MergerFS ? 
If I switch the binds to "regular" FS directories, I have no issues.
If I copy these directories to an MergerFS mount and use them, got the same issues back.

I know there are issues between MergerFS and nmap()

**Comment by unintended-consequences** [comment]
Yup that could be it. I am using mergerFS. Will test shortly.
