### ISSUE TITLE
[BUG] PDF consumption fails due to error in ghostscript 

### ISSUE THREAD

**Issue by Cartman84** [jonaswinkler/paperless-ng#1379]
Paperless-NG does not let me import new files anymore. Neither drag and drop on webinterface nor moving files to the paperless-import watchfolder does work and fails with the same issue. I think it somehow has issues with the OCR functionality, but I am not sure. It affects all files I want to upload (pdf), even invoices which I receive monthly and have been successfully imported all the time - until 3 weeks ago.

`[2021-10-12 10:18:01,829] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/test.pdf to the task queue.
10:18:01 [Q] INFO Enqueued 1
10:18:01 [Q] INFO Process-1:13 processing [test.pdf]
[2021-10-12 10:18:01,890] [INFO] [paperless.consumer] Consuming test.pdf
[2021-10-12 10:18:06,108] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR

[2021-10-12 10:18:06,108] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR

[2021-10-12 10:18:08,163] [ERROR] [ocrmypdf._exec.ghostscript] GPL Ghostscript 9.53.3 (2020-10-01)

Copyright (C) 2020 Artifex Software, Inc. All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GPL Ghostscript 9.53.3: **** Could not open temporary file /tmp/gs_DJUhxU
**** Unable to open the initial device, quitting.

[2021-10-12 10:18:08,170] [ERROR] [paperless.consumer] Error while consuming document test.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 240, in generate_pdfa
p = run_polling_stderr(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 94, in run_polling_stderr
raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)
subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/fix_docinfo.pdf', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
ocrmypdf.ocr(**args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 374, in run_pipeline
exec_concurrent(context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 298, in exec_concurrent
pdf = post_process(pdf, context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 230, in post_process
pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 729, in convert_to_pdfa
context.plugin_manager.hook.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
return outcome.get_result()
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
res = hook_impl.function(*args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 91, in generate_pdfa
ghostscript.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 254, in generate_pdfa
raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed

10:18:08 [Q] INFO Process-1:13 stopped doing work
10:18:08 [Q] ERROR Failed [test.pdf] - test.pdf: Error while consuming document test.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed : Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 240, in generate_pdfa
p = run_polling_stderr(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 94, in run_polling_stderr
raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)
subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/fix_docinfo.pdf', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
ocrmypdf.ocr(**args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 374, in run_pipeline
exec_concurrent(context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 298, in exec_concurrent
pdf = post_process(pdf, context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 230, in post_process
pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 729, in convert_to_pdfa
context.plugin_manager.hook.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
return outcome.get_result()
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
res = hook_impl.function(*args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 91, in generate_pdfa
ghostscript.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 254, in generate_pdfa
raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 288, in main_wrap
raise exc_info[1]
File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 74, in consume_file
document = Consumer().try_consume_file(
File "/usr/src/paperless/src/documents/consumer.py", line 266, in try_consume_file
self._fail(
File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: test.pdf: Error while consuming document test.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed

[2021-10-12 10:18:08,163] [ERROR] [ocrmypdf._exec.ghostscript] GPL Ghostscript 9.53.3 (2020-10-01)

Copyright (C) 2020 Artifex Software, Inc. All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GPL Ghostscript 9.53.3: **** Could not open temporary file /tmp/gs_DJUhxU
**** Unable to open the initial device, quitting.

[2021-10-12 10:18:08,170] [ERROR] [paperless.consumer] Error while consuming document test.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 240, in generate_pdfa
p = run_polling_stderr(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 94, in run_polling_stderr
raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)
subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/fix_docinfo.pdf', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
ocrmypdf.ocr(**args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 374, in run_pipeline
exec_concurrent(context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 298, in exec_concurrent
pdf = post_process(pdf, context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 230, in post_process
pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 729, in convert_to_pdfa
context.plugin_manager.hook.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
return outcome.get_result()
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
res = hook_impl.function(*args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 91, in generate_pdfa
ghostscript.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 254, in generate_pdfa
raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed

10:18:08 [Q] INFO Process-1:13 stopped doing work
10:18:08 [Q] ERROR Failed [test.pdf] - test.pdf: Error while consuming document test.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed : Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 240, in generate_pdfa
p = run_polling_stderr(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 94, in run_polling_stderr
raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)
subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/fix_docinfo.pdf', '/usr/src/paperless/src/ocrmypdf.io.8bhoc0ox/pdfa.ps']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
ocrmypdf.ocr(**args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 374, in run_pipeline
exec_concurrent(context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 298, in exec_concurrent
pdf = post_process(pdf, context, executor)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 230, in post_process
pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 729, in convert_to_pdfa
context.plugin_manager.hook.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
return outcome.get_result()
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
res = hook_impl.function(*args)
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 91, in generate_pdfa
ghostscript.generate_pdfa(
File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 254, in generate_pdfa
raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 288, in main_wrap
raise exc_info[1]
File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 74, in consume_file
document = Consumer().try_consume_file(
File "/usr/src/paperless/src/documents/consumer.py", line 266, in try_consume_file
self._fail(
File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: test.pdf: Error while consuming document test.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed

10:18:08 [Q] INFO recycled worker Process-1:13
10:18:08 [Q] INFO Process-1:15 ready for work at 330`

**Relevant information**
 - Host OS of the machine running paperless: running in this docker
 - Browser Chrome / Safari
 - Version 1.5.0
 - Installation method: docker
 - no configuration changes, docker config as attached
![2021-10-12 10_26_56-Window](https://user-images.githubusercontent.com/65272824/136920248-9d87f4f3-ae54-444a-b9b7-4c40409851cc.jpg)

**Comment by mcdax** [comment]
Hi,
I experience the same issue.
Did you find any solution?

**Comment by Cartman84** [comment]
> Hi, I experience the same issue. Did you find any solution?
> 
> EDIT: Ok, after stopping the container, pruning everything (docker system prune --all) and adding the image to Unraid again (via "add Container" and selecting paperless-ng as template), it seems to work.

By pruning everything, I really delete everything not only this docker, don‘t I? 

I still don‘t have a solution. Unfortunately it seems that there is also no support from the dev to this project anymore, I am thinking about to switch to another dms solution anyway.

**Comment by mcdax** [comment]
"Could not open temporary file /tmp/gs_DJUhxU" indicates that there might be an issue with the permissions for "/tmp/...".

Some other docker containers had the same issue in my case, so I don't think that this is a problem with paperless.
