### ISSUE TITLE
JPG Invalid Rotation

### ISSUE THREAD

**Issue by gummipunkt** [jonaswinkler/paperless-ng#1431]
webserver_1  | [2021-11-08 15:28:33,896] [ERROR] [paperless.consumer] Error while consuming document IMG_20211108_071703.jpg: ExifOrientationError: Invalid rotation (0)
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
webserver_1  |     ocrmypdf.ocr(**args)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
webserver_1  |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 354, in run_pipeline
webserver_1  |     origin_pdf = triage(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 143, in triage
webserver_1  |     triage_image_file(input_file, output_file, options)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 99, in triage_image_file
webserver_1  |     img2pdf.convert(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 2102, in convert
webserver_1  |     ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 1388, in read_images
webserver_1  |     color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 1227, in get_imgmetadata
webserver_1  |     raise ExifOrientationError("Invalid rotation (%d)" % value)
webserver_1  | img2pdf.ExifOrientationError: Invalid rotation (0)
webserver_1  |
webserver_1  | During handling of the above exception, another exception occurred:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
webserver_1  |     document_parser.parse(self.path, mime_type, self.filename)
webserver_1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
webserver_1  |     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
webserver_1  | documents.parsers.ParseError: ExifOrientationError: Invalid rotation (0)
webserver_1  | 15:28:33 [Q] INFO Process-1:8 stopped doing work
webserver_1  | 15:28:33 [Q] ERROR Failed [IMG_20211108_071703.jpg] - IMG_20211108_071703.jpg: Error while consuming document IMG_20211108_071703.jpg: ExifOrientationError: Invalid rotation (0) : Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 241, in parse
webserver_1  |     ocrmypdf.ocr(**args)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 340, in ocr
webserver_1  |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 354, in run_pipeline
webserver_1  |     origin_pdf = triage(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 143, in triage
webserver_1  |     triage_image_file(input_file, output_file, options)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 99, in triage_image_file
webserver_1  |     img2pdf.convert(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 2102, in convert
webserver_1  |     ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 1388, in read_images
webserver_1  |     color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/img2pdf.py", line 1227, in get_imgmetadata
webserver_1  |     raise ExifOrientationError("Invalid rotation (%d)" % value)
webserver_1  | img2pdf.ExifOrientationError: Invalid rotation (0)
webserver_1  |
webserver_1  | During handling of the above exception, another exception occurred:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 288, in main_wrap
webserver_1  |     raise exc_info[1]
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
webserver_1  |     document_parser.parse(self.path, mime_type, self.filename)
webserver_1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 290, in parse
webserver_1  |     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
webserver_1  | documents.parsers.ParseError: ExifOrientationError: Invalid rotation (0)
webserver_1  |
webserver_1  | During handling of the above exception, another exception occurred:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 74, in consume_file
webserver_1  |     document = Consumer().try_consume_file(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 266, in try_consume_file
webserver_1  |     self._fail(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
webserver_1  |     raise ConsumerError(f"{self.filename}: {log_message or message}")
webserver_1  | documents.consumer.ConsumerError: IMG_20211108_071703.jpg: Error while consuming document IMG_20211108_071703.jpg: ExifOrientationError: Invalid rotation (0)

**Comment by JoergPalmer** [comment]
I had this problem as well for some images. Most likely it's a problem with the image itself, in particular the orientation value in the exif data. More on the valid rotations here: https://jdhao.github.io/2019/07/31/image_rotation_exif_info/

My guess is that this is a problem of the application that created the image. Is it a scan app on the smart phone? For myself, the scan app turned out to be the problem. After I tuned the orientation value manually, paperless could consume the image.
