### ISSUE TITLE
[BUG] Consuming from smb share sometimes fails with "file not found" errors

### ISSUE THREAD

**Issue by mwiederhold** [jonaswinkler/paperless-ng#1447]
**Describe the bug**
I use an smb share as the consumption directory. The consumer always picks up new documents and starts processing them. Often, the task eventually fails with `[Errno 2] No such file or directory: '/usr/src/paperless/src/../consume/Scan19112021193259.pdf'`. 

PDF files are copied to the share in one piece. I have set `PAPERLESS_CONSUMER_POLLING: 30`, so inotify is disabled.

**To Reproduce**
1. Set up paperless via docker-compose
2. Set up smb share as consumption directory 
3. Add pdf file to consumption directory
4. Check the webserver log to see Error (in majority of cases)

**Expected behavior**
- Document is deleted from consumption directory
- Consumption task finishes without error
- Document is added to database

**Actual behavior**
- Document is deleted from consumption directory
- Consumption task finishes WITH error
- Document is NOT added to database

**Webserver logs**
```
[2021-11-19 19:33:18,697] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/Scan19112021193259.pdf to remain unmodified

[2021-11-19 19:33:23,703] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/Scan19112021193259.pdf to the task queue.

[2021-11-19 19:33:23,881] [INFO] [paperless.consumer] Consuming Scan19112021193259.pdf

[2021-11-19 19:33:23,890] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2021-11-19 19:33:23,905] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2021-11-19 19:33:23,914] [DEBUG] [paperless.consumer] Parsing Scan19112021193259.pdf...

[2021-11-19 19:33:24,895] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/src/../consume/Scan19112021193259.pdf

[2021-11-19 19:33:25,117] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/Scan19112021193259.pdf', 'output_file': '/tmp/paperless/paperless-9bsrj6ku/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-9bsrj6ku/sidecar.txt'}

[2021-11-19 19:33:31,516] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2021-11-19 19:33:32,331] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-9bsrj6ku/archive.pdf

[2021-11-19 19:33:32,332] [DEBUG] [paperless.consumer] Generating thumbnail for Scan19112021193259.pdf...

[2021-11-19 19:33:32,346] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-9bsrj6ku/archive.pdf[0] /tmp/paperless/paperless-9bsrj6ku/convert.png

[2021-11-19 19:33:34,855] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-9bsrj6ku/convert.png -out /tmp/paperless/paperless-9bsrj6ku/thumb_optipng.png

[2021-11-19 19:33:40,278] [ERROR] [paperless.consumer] The following error occured while consuming Scan19112021193259.pdf: [Errno 2] No such file or directory: '/usr/src/paperless/src/../consume/Scan19112021193259.pdf'

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 287, in try_consume_file

    document = self._store(

  File "/usr/src/paperless/src/documents/consumer.py", line 372, in _store

    stats = os.stat(self.path)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/src/../consume/Scan19112021193259.pdf'

[2021-11-19 19:33:40,280] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-9bsrj6ku
```

**Relevant information**
 - Debian 10
 - Firefox
 - 1.5.0
 - Installation method: docker-compose.postgres-tika
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`:

***docker-compose.yml***
```yaml
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - internal

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: <<secret>>
    networks:
      - internal

  webserver:
    image: jonaswinkler/paperless-ng:1.5.0
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8083:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /mnt/smb/paperless/export:/usr/src/paperless/export
      - /mnt/smb/paperless/inbox:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPASS: <<secret>>
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: <<secret>>
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_POLLING: 30
    labels:
      - traefik.http.routers.paperless.rule=Host(`<<secret>>`)
      - traefik.port=8000
    networks:
      - proxy
      - internal

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1
    networks:
      - internal

  tika:
    image: apache/tika
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
  proxy:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/hdd-storage/docker/paperless/data'
  media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/hdd-storage/docker/paperless/media'
  pgdata:
```

***docker-compose.env***
```env
PAPERLESS_SECRET_KEY=<<secret>>
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
````

**Comment by mwiederhold** [comment]
Huh... I cannot reproduce this error using another samba server. So this might be an issue with my file share. Sorry for the inconvenience, I am closing this.

**Comment by cmuench** [comment]
I have the same issue on my Synlogy NAS. Also using a SMB Share.
Works on my developer machine without a SMB share. Both are running the equal docker setup.
I will try to figure out more...
