### ISSUE TITLE
Data migration from sqlite to Postgres fails

### ISSUE THREAD

**Issue by Cludch** [jonaswinkler/paperless-ng#146]
Hey,

(it's me again).
I have 400 working documents in my -ng instance. The next step was to migrate SQLite to Postgres.
After I setup everything and started a bash within the paperless-ng container (which is linked to the postgres database), I run into the following error:
```
INFO 2020-12-16 20:18:10,377 filelock Lock 140092644583696 released on /usr/src/paperless/src/../media/media.lock
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(128)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
```

I guess some title or something seems to be to long?

**Comment by jonaswinkler** [comment]
Yes. PostgreSQL enforces field length restrictions, sqlite does not.

There isn't really anything I can do, except raising the limit.

**Comment by jonaswinkler** [comment]
I'll probably have the length restrictions on these fields raised a little bit. For the time being, you could either
- continue using SQlite, which is perfectly fine for paperless (people have successfully used SQLite for much larger setups than this)
- Identify the titles in question with the list view and shorten them. The current limit is 128 characters on titles and names. That's what it has always been and I've not yet considered to change that.
