### ISSUE TITLE
Error when trying to restore export

### ISSUE THREAD

**Issue by jcpsantiago** [jonaswinkler/paperless-ng#165]
To make sure things work, I exported documents with `document_exporter` and copied the folder to another computer, got the docker files again and

```
docker-compose run --rm webserver document_importer ../export
Creating paperless_webserver_run ... done
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [256 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7856 B]
Fetched 8410 kB in 4s (2214 kB/s)                        
Reading package lists... Done
package tesseract-ocr-deu already installed!
package tesseract-ocr-eng already installed!
Waiting for PostgreSQL to start...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
INFO 2020-12-20 21:39:16,535 filelock Lock 139648920693776 acquired on /usr/src/paperless/src/../media/media.lock
INFO 2020-12-20 21:39:16,537 filelock Lock 139648920693776 released on /usr/src/paperless/src/../media/media.lock
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'correspondent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 52, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 803, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 248, in update_filename_and_move_files
    if not validate_move(instance, old_source_path, new_source_path):
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 208, in validate_move
    f"Document {str(instance)}: File {old_path} has gone.")
  File "/usr/src/paperless/src/documents/models.py", line 211, in __str__
    if self.correspondent and self.title:
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
documents.models.DoesNotExist: Problem installing fixture '/usr/src/paperless/src/../export/manifest.json': Correspondent matching query does not exist.
```

**Comment by jonaswinkler** [comment]
Thanks for reporting. Noted. Will address in the next release. Thought I fixed that one long ago, apparently not.

**Comment by jcpsantiago** [comment]
thanks :D works like a charm! time to warm up the shredder  👹

**Comment by jonaswinkler** [comment]
Great! :)
