### ISSUE TITLE
[BUG] Database migrations error

### ISSUE THREAD

**Issue by Betaglobulin** [jonaswinkler/paperless-ng#1705]
Hi, 
im trying to install paperless-ng on my raspberry pi. When running the superuser creation command after following the guide for the docker install, the following error appears. How do i fix this:

 docker-compose run --rm webserver createsuperuser
Starting paperless-ng_broker_1 ... done
Paperless-ng docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped

Cheer Gamma

**Comment by rYR79435** [comment]
I cannot help you with your problem, but since you're installing paperless, you might be interested in knowing that this project is stale (abandoned?).
There's been active development by the community over at [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx). Hope installing that works.
