### ISSUE TITLE
[BUG] Redis - Authentication required Unraid Docker

### ISSUE THREAD

**Issue by horphi0815** [jonaswinkler/paperless-ng#1710]
Hi,

Redis requires a PW.

How can i add this, to the Docker in Unraid?

`[2022-06-06 20:33:39,929] [ERROR] [paperless.management.consumer] Error while consuming document
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 69, in _consume
    async_task("documents.tasks.consume_file",
  File "/usr/local/lib/python3.9/site-packages/django_q/tasks.py", line 73, in async_task
    enqueue_id = broker.enqueue(pack)
  File "/usr/local/lib/python3.9/site-packages/django_q/brokers/redis_broker.py", line 18, in enqueue
    return self.connection.rpush(self.list_key, task)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 2016, in rpush
    return self.execute_command('RPUSH', name, *values)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 484, in read_response
    raise response
redis.exceptions.AuthenticationError: Authentication required.`

BR

**Comment by freaky33** [comment]
This repo is no longer maintained. You should use paperless-ngx.

But for your issue: Try this as your PAPERLESS_REDIS: redis://:[PASSWORD]@[IP]:6379
