### ISSUE TITLE
OSError: [Errno 19] No such device

### ISSUE THREAD

**Issue by PhrantiK** [jonaswinkler/paperless-ng#216]
Getting the following when trying to import documents either through the consume directory or through the web interface. 

Everything seems to be running ok, there's no other errors in the container logs I can see to try and troubleshoot. 

Thanks!

```
[Errno 19] No such device : Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 184, in try_consume_file
classifier=classifier
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in send
for receiver in self._live_receivers(sender)
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
for receiver in self._live_receivers(sender)
File "/usr/src/paperless/src/documents/signals/handlers.py", line 342, in add_to_index
index.add_or_update_document(document)
File "/usr/src/paperless/src/documents/index.py", line 118, in add_or_update_document
update_document(writer, document)
File "/usr/src/paperless/src/documents/index.py", line 105, in update_document
modified=doc.modified,
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 1024, in update_document
self._record("update_document", args, kwargs)
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 1001, in _record
getattr(self.writer, method)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 483, in update_document
with self.searcher() as s:
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 297, in searcher
return Searcher(self.reader(), **kwargs)
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 639, in reader
self.generation, reuse=reuse)
File "/usr/local/lib/python3.7/site-packages/whoosh/index.py", line 529, in _reader
return segreader(segments[0])
File "/usr/local/lib/python3.7/site-packages/whoosh/index.py", line 524, in segreader
generation=generation)
File "/usr/local/lib/python3.7/site-packages/whoosh/reading.py", line 610, in __init__
files = segment.open_compound_file(storage)
File "/usr/local/lib/python3.7/site-packages/whoosh/codec/base.py", line 570, in open_compound_file
return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)
File "/usr/local/lib/python3.7/site-packages/whoosh/filedb/compound.py", line 75, in __init__
self._source = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)
OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
override_tag_ids=override_tag_ids)
File "/usr/src/paperless/src/documents/consumer.py", line 222, in try_consume_file
raise ConsumerError(e)
documents.consumer.ConsumerError: [Errno 19] No such device```

**Comment by jonaswinkler** [comment]
- How did you install paperless?
- What is the OS of your host system?

**Comment by PhrantiK** [comment]
Installed using your docker compose example (postgres). 

Ubuntu 20.04.1 running in a proxmox VM. 

Checked memory and increased it to test but still the same error unfortunately. 

Appreciate your help!

**Comment by jonaswinkler** [comment]
Seems like some issue with memory-mapped files and this particular VM solution. This comes from the search index library. There's an option to disable that and use normal files instead.

I could provide a configuration option for that, however: I've got no idea about performance implications.

**Comment by PhrantiK** [comment]
Happy to test and see how we go if it's not too much of a hassle.

**Comment by hydriniumh2** [comment]
Just wanted to chime in that I'm getting the same error running the Postgres docker on Stretch Debian

**Comment by jonaswinkler** [comment]
> Just wanted to chime in that I'm getting the same error running the Postgres docker on Stretch Debian

@hydriniumh2 Are you getting *exactly* the same error? Care to share any logs? What version of docker and docker-compose are you running?

**Comment by hydriniumh2** [comment]
Yes, here is one log:
```
[Errno 19] No such device : Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 232, in try_consume_file
classifier=classifier
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in send
for receiver in self._live_receivers(sender)
File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
for receiver in self._live_receivers(sender)
File "/usr/src/paperless/src/documents/signals/handlers.py", line 308, in add_to_index
index.add_or_update_document(document)
File "/usr/src/paperless/src/documents/index.py", line 115, in add_or_update_document
update_document(writer, document)
File "/usr/src/paperless/src/documents/index.py", line 100, in update_document
modified=doc.modified,
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 1024, in update_document
self._record("update_document", args, kwargs)
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 1001, in _record
getattr(self.writer, method)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 483, in update_document
with self.searcher() as s:
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 297, in searcher
return Searcher(self.reader(), **kwargs)
File "/usr/local/lib/python3.7/site-packages/whoosh/writing.py", line 639, in reader
self.generation, reuse=reuse)
File "/usr/local/lib/python3.7/site-packages/whoosh/index.py", line 529, in _reader
return segreader(segments[0])
File "/usr/local/lib/python3.7/site-packages/whoosh/index.py", line 524, in segreader
generation=generation)
File "/usr/local/lib/python3.7/site-packages/whoosh/reading.py", line 610, in __init__
files = segment.open_compound_file(storage)
File "/usr/local/lib/python3.7/site-packages/whoosh/codec/base.py", line 570, in open_compound_file
return CompoundStorage(dbfile, use_mmap=storage.supports_mmap)
File "/usr/local/lib/python3.7/site-packages/whoosh/filedb/compound.py", line 75, in __init__
self._source = mmap.mmap(fileno, 0, access=mmap.ACCESS_READ)
OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
override_tag_ids=override_tag_ids)
File "/usr/src/paperless/src/documents/consumer.py", line 271, in try_consume_file
raise ConsumerError(e)
documents.consumer.ConsumerError: [Errno 19] No such device
```
```
>cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
> docker --version
Docker version 19.03.14, build 5eb3275d40
> docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6
```
I do have the paperless directories mounted on a mergerfs directory, perhaps thats the issue

**Comment by hydriniumh2** [comment]
Yeah, my bad. I changed the data and media folders to non-union filesystems and it started working.

**Comment by jonaswinkler** [comment]
Alright. I'll add that to the troubleshooting section.

**Comment by PhrantiK** [comment]
> I do have the paperless directories mounted on a mergerfs directory, perhaps thats the issue

Fixed here too - didn't think of that! Nice one @hydriniumh2
