### ISSUE TITLE
0.9.12: Permission Error /tmp/tika.log

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#290]
Setup: paperless-ng via docker-compose, Gotenborg and Tika separate Docker-Container (not in Docker-Compose.yml of paperless-ng!).

Couldn't expect to test the new version with Tika and Gotenborg. Unfortunately there is an error, which stops using paperless-ng for me:
`Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless_tika/apps.py", line 3, in <module>
    from paperless_tika.signals import tika_consumer_declaration
  File "/usr/src/paperless/src/paperless_tika/signals.py", line 1, in <module>
    from .parsers import TikaDocumentParser
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 9, in <module>
    from tika import parser
  File "/usr/local/lib/python3.7/site-packages/tika/parser.py", line 19, in <module>
    from .tika import parse1, callServer, ServerEndpoint
  File "/usr/local/lib/python3.7/site-packages/tika/tika.py", line 155, in <module>
    fileHandler = logging.FileHandler(log_file)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/tika.log'
`

I just changed the Environment-Entry for Tika and Gotenborg, everything else is unchanged and worked perfectly before. 
This error occurs if i set Tika enabled or disabled.
When i use docker-compose for paperless and add tika and gotenborg-container, the error does occur too.

**Comment by jonaswinkler** [comment]
Check #271, could be something similar.

**Comment by andbez** [comment]
This error occurs immediately when the webserver is started. There are no files in the consume-dir.

**Comment by kaiserbene** [comment]
same behaviour here when upgrading from 0.9.11 to 0.9.12. Only thing I changed was 11 to 12 in docker-compose.yml. Using the sqlite version... going back to 11 and the container is up again

**Comment by mikkelnl** [comment]
Same issue here.

**Comment by growse** [comment]
For those of you running this on k8s, I worked around this by mounting an `emptyDir` volume on `/tmp`.

**Comment by tohn** [comment]
Same issue here. But I don't use tika (yet), so only webserver and postgres. And it's a new installation.  
Not sure if this could be a problem, but I'm using the macOS mappings for my user:
```bash
USERMAP_UID=1078972722
USERMAP_GID=5674437
```

**Comment by jonaswinkler** [comment]
I'm sorry. The library used for tika interaction is creating a temporary file during build time, which is part of the image. Then, at runtime, paperless is unable to overwrite that file when custom UIDs / GIDs are used.

Don't get me wrong, I'm testing stuff on my own installation before I publish something, but I'm not using every single option, and this is still pretty much a one-man show.

**Comment by andbez** [comment]
@jonaswinkler I (and i think others too) don't get you wrong. I know what your work means and appreciate your work. It will make my everyday life easier! And i am very happy to support your work. You (and the other devs) are doing a very good job! Keep on the good work! I already imported over 2000 Documents in paperless-ng!
