### ISSUE TITLE
Docker doesn't start since update yesterday

### ISSUE THREAD

**Issue by sturmstar** [jonaswinkler/paperless-ng#294]
Log is following:

Mapping UID and GID for paperless:paperless to 99:100
Traceback (most recent call last):
File "manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
django.setup()
File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
app_config = AppConfig.create(entry)
File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
module = import_module(entry)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/src/paperless/src/paperless_tika/apps.py", line 3, in <module>
from paperless_tika.signals import tika_consumer_declaration
File "/usr/src/paperless/src/paperless_tika/signals.py", line 1, in <module>
from .parsers import TikaDocumentParser
File "/usr/src/paperless/src/paperless_tika/parsers.py", line 9, in <module>
from tika import parser
File "/usr/local/lib/python3.7/site-packages/tika/parser.py", line 19, in <module>
from .tika import parse1, callServer, ServerEndpoint
File "/usr/local/lib/python3.7/site-packages/tika/tika.py", line 155, in <module>
fileHandler = logging.FileHandler(log_file)
File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/tika.log'

What was the latest version of the docker - I don't know - so I stepped back to 0.9.9 this is working

thanks

**Comment by jonaswinkler** [comment]
See #290, fixed in 0.9.13.
