### ISSUE TITLE
no such column: documents_tag.slug

### ISSUE THREAD

**Issue by alex-phillips** [jonaswinkler/paperless-ng#341]
Software seems to run fine, able to consume documents placed into the consume directory, but when I came back 2 days later to view documents, no documents are returned with an error code of 500. Debug on displays the following for these requests:

![image](https://user-images.githubusercontent.com/3135216/104597757-b7b7b680-5643-11eb-932b-1669ee634ad6.png)

Here is the text output from the error:

```
Environment:


Request Method: GET
Request URL: https://paperless-ng.mydomain.com/api/tags/?page=1&page_size=100000

Django Version: 3.1.3
Python Version: 3.8.5
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'django_extensions',
 'paperless',
 'documents.apps.DocumentsConfig',
 'paperless_tesseract.apps.PaperlessTesseractConfig',
 'paperless_text.apps.PaperlessTextConfig',
 'paperless_mail.apps.PaperlessMailConfig',
 'django.contrib.admin',
 'rest_framework',
 'django_filters',
 'django_q']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such column: documents_tag.slug) was the direct cause of the following exception:
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/usr/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/usr/lib/python3.8/site-packages/rest_framework/pagination.py", line 218, in paginate_queryset
    return list(self.page)
  File "/usr/lib/python3.8/site-packages/django/core/paginator.py", line 143, in __len__
    return len(self.object_list)
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /api/tags/
Exception Value: no such column: documents_tag.slug
```

**Comment by jonaswinkler** [comment]
What version?

Docker or bare metal?

**Comment by alex-phillips** [comment]
Would something like this be taken care of via a migration in the future? It's likely that I installed this back with an older version but have since upgraded the code. Running `python3 manage.py migrate` shows everything up-to-date.

**Comment by alex-phillips** [comment]
Also, is there somewhere in the UI or code that will tell me which version I'm currently running?

**Comment by jonaswinkler** [comment]
Version is shown in the bottom left corner:

![image](https://user-images.githubusercontent.com/17569239/104601249-4a734800-567a-11eb-8579-fc17a4ecc843.png)

This was added in 0.9.7. Version is also listed in the code, at `src/paperless/version.py`.

Updating database schemas is already taken care of automatically when using docker. If not running bare metal, the migrate script has to be invoked manually on updates.

**Comment by alex-phillips** [comment]
Yes, I was invoking the migration script manually before every startup. Will rebuild with latest code and see what I get. Thanks for the info.

**Comment by jonaswinkler** [comment]
Is this resolved?

**Comment by alex-phillips** [comment]
Yes, thanks.
