### ISSUE TITLE
UnsupportedImageFormatError when processing certain TIFF images

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#398]
Same here on a docker container.
I copy manually  a bunch of TIFF files produced by my scanner. There are some, which result in failed tasks with similar logs:

```
: Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 176, in parse
ocrmypdf.ocr(**ocr_args)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/api.py", line 326, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_sync.py", line 353, in run_pipeline
original_filename, start_input_file, work_folder / 'origin.pdf', options
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 143, in triage
triage_image_file(input_file, output_file, options)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 82, in triage_image_file
raise UnsupportedImageFormatError()
ocrmypdf.exceptions.UnsupportedImageFormatError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 179, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 197, in parse
raise ParseError(e)
documents.parsers.ParseError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
override_tag_ids=override_tag_ids)
File "/usr/src/paperless/src/documents/consumer.py", line 196, in try_consume_file
raise ConsumerError(e)
documents.consumer.ConsumerError
```
If we inspect via info, they seem to be valid TIFFs? 
`file DB\ Fahrt.tiff --mime-type
DB Fahrt.tiff: image/tiff`
This issue occures on single and multipage tiffs, which seem to valid:
```
tiffinfo DB\ Fahrt.tiff
TIFF Directory at offset 0x7331cc (7549388)
  Image Width: 3300 Image Length: 2550
  Bits/Sample: 8
  Compression Scheme: AdobeDeflate
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  FillOrder: msb-to-lsb
  Samples/Pixel: 4
  Rows/Strip: 2550
  Planar Configuration: single image plane
```
I added files again and again, with altered names, but error persists. Files van be viewed fine :confused:

_Originally posted by @Matthias84 in https://github.com/jonaswinkler/paperless-ng/issues/176#issuecomment-763821408_

**Comment by jonaswinkler** [comment]
This is an issue with Pillow (the library used for processing images in Python) not supporting certain TIFF formats.

See also https://github.com/python-pillow/Pillow/issues/5114. An issue is described that causes the above error.

**Comment by Matthias84** [comment]
It seems like tiffcp used in my merge script causes some irregular TIFF files that include fake pages and inconsistent compressions, alpha channels etc. https://github.com/BitMiracle/libtiff.net/issues/61 
If I open + save via GIMP, they are processed properly again :smiley:

**Comment by jonaswinkler** [comment]
Good!

I've managed to `convert` (ImageMagick) some PDF documents into multi page TIFFs, and these don't process as well. I'll keep this open for now.
