### ISSUE TITLE
Checking Email Accounts Fails

### ISSUE THREAD

**Issue by WBWBW** [jonaswinkler/paperless-ng#419]
I get this in the failed task when checking a gmail account: 

`
[Errno -2] Name or service not known : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/paperless_mail/tasks.py", line 12, in process_mail_accounts
account)
File "/usr/src/paperless/src/paperless_mail/mail.py", line 157, in handle_mail_account
account.imap_security) as M:
File "/usr/src/paperless/src/paperless_mail/mail.py", line 97, in get_mailbox
mailbox = MailBox(server, port)
File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 230, in __init__
super().__init__()
File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 26, in __init__
self.box = self._get_mailbox_client()
File "/usr/local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 245, in _get_mailbox_client
return imaplib.IMAP4_SSL(self._host, self._port, self._keyfile, self._certfile, self._ssl_context)
File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
IMAP4.__init__(self, host, port)
File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
self.open(host, port)
File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
IMAP4.open(self, host, port)
File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
self.sock = self._create_socket()
File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket
sock = IMAP4._create_socket(self)
File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket
return socket.create_connection((host, self.port))
File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known`

**Comment by jonaswinkler** [comment]
This error means that name resolution for the IMAP server failed.

**Comment by WBWBW** [comment]
Thanks. I figured it out. For some reason my docker bridged container had no internet access. Great project btw! Thanks again.

**Comment by palitu** [comment]
How did you solve it?

**Comment by WBWBW** [comment]
> How did you solve it?

Changed my container network to host as opposed to bridge.
