### ISSUE TITLE
Not migrating from paperless or importing paperless files

### ISSUE THREAD

**Issue by tanderson1992** [jonaswinkler/paperless-ng#451]
**Describe the bug**
After migration from paperless, paperless-ng has no documents. Additionally, attempting to import from the /export folder fails.

**To Reproduce**
Following https://paperless-ng.readthedocs.io/en/latest/setup.html?highlight=docker%20pull#migration-to-paperless-ng
At Step 3, download image and .env/.yml files to paperless-ng instead of existing paperless-master
At Step 7, `docker-compose run --rm webserver document_index reindex` runs with no errors. There's also no indication previous paperless files were found and updated.
After Step 8 and a cache refresh, the new paperless-ng frontend starts. There are no documents in the library.

As part of troubleshooting, I tried to import from the paperless exported files. I didn't expect it to work but tried anyway.

`docker-compose run --rm webserver document_importer ../export` results in the following error:

```
Executing management command document_importer ../export
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/options.py", line 575, in get_field
    return self.fields_map[field_name]
KeyError: 'file_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/python.py", line 117, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/options.py", line 577, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Document has no field named 'file_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 72, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 172, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/json.py", line 74, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/usr/src/paperless/src/../export/manifest.json':
```

**Expected behavior**
From the instructions, I expected paperless documents to be migrated to paperless-ng. Apparently the database migration from Step 7 didn't actually happen. As far as I can tell, no paperless files were changed. I was able to stop paperless-ng, restart paperless, and see my original 929-document database.

**Relevant information**
 - Host OS of the machine running paperless: QNAP NAS using docker
 - Browser Firefox
 - Version paperless-ng:1.0.0
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`. 
Added: `PAPERLESS_FORGIVING_OCR="true"` to `docker-compose.env`

**Comment by jonaswinkler** [comment]
1. Did you use docker compose as well when running old paperless?
2. Please post the output of `docker volume ls | grep _data`. You may want to exclude results if you're sure they are not related to paperless. This will not modify anything.
3. Importing an export from an older version into a newer version does not work. The database format changed, and the data from the old export needs to be migrated.

**Comment by tanderson1992** [comment]
1. Yes I did. I ran docker-compose down in Step 1, and it correctly closed my old paperless instance.
2.
```
docker volume ls | grep _data
local               paperless-master_data
local               paperless_data
```
I'm wondering if this is the issue here. I can't remember if I called it paperless-master when I installed back in July 2020 or if the docker install method I used created the folder like that.

3. I didn't think it would work because of the database format, I wanted to include all the troubleshooting steps I tried, which no doubt reveal my lack of experience with docker.

**Comment by jonaswinkler** [comment]
> docker volume ls | grep _data
> local               paperless-master_data
> local               paperless_data

That's the issue. adjust the .env file and set the project name to paperless-master. That way, paperless-ng will reuse your old volumes and update them. Remember to make a backup.

**Comment by jonaswinkler** [comment]
Also, please close this once you managed to migrate successfully.

**Comment by tanderson1992** [comment]
That did the trick, thank you! Again, I don't remember if I named the folder paperless-master when I copied the files there months ago, but including the proper name in .env resulted in the migration of all 929 documents. Now I need to delete the paperless_data volume. Thank you again, I like the ng look so far and will fill out the survey after I've had a chance to properly test drive it.
