### ISSUE TITLE
[BUG] Detected mime type: inode/x-empty for very small documents

### ISSUE THREAD

**Issue by C0nsultant** [jonaswinkler/paperless-ng#472]
**Describe the bug**
Uploading very small documents (<4kB) intermittently leads to `Detected mime type: inode/x-empty`.

Tracking potentially unsolved problems discovered in #411.

**To Reproduce**
This can not be reproduced deterministically (I expect it to be a race condition or behaviour outlined in https://github.com/jonaswinkler/paperless-ng/pull/411#issuecomment-770187870).

1. Create a `.txt` file containing only a few characters (say, less than 64).
2. Upload the file either through the frontend or the API.
3. Observe that only two log lines are produced and the document is never consumed:

> Consuming REPRODUCER.txt
Detected mime type: inode/x-empty

**Expected behavior**
Detect mime type for all documents properly, consume all valid documents.

**Relevant information**
 - Version `1.0.0`

**Comment by jonaswinkler** [comment]
Unable to reproduce with a text file containing "abc".

However, I addressed the relevant section in the API and made sure that the file handle is closed before pushing a new consumption task.

**Comment by C0nsultant** [comment]
Your change should definitely close the problem. I will try shrinking the file used for testing again to verify.

**Comment by Cantello** [comment]
I was trying to test why the consumer was consuming some documents and not others, I came across a (possibly) similar error.
This instance of paperless-ng 1.4.3 runs in a docker on Ubuntu Server 20.04 and the document that caused this was a regular scanned document with two pages, 350kb in PDF-1.7 format created by my scanner. Is this relevant (due to the same mime type)?

`Scan_20210519_193110.pdf: Unsupported mime type inode/x-empty : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
task_id=task_id
File "/usr/src/paperless/src/documents/consumer.py", line 211, in try_consume_file
f"Unsupported mime type {mime_type}"
File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: Scan_20210519_193110.pdf: Unsupported mime type inode/x-empty`

**Comment by jonaswinkler** [comment]
How did you upload the document to paperless?

**Comment by Cantello** [comment]
Via the consumer directory.
