### ISSUE TITLE
[BUG] Upload odt: Error while converting document to PDF

### ISSUE THREAD

**Issue by telsch** [jonaswinkler/paperless-ng#535]
**Describe the bug**
Uploading an odt Document raising an exception.

**To Reproduce**
1. Go to Dashboard
2. Click on Browse files
3. Watch `docker logs -f paperless_webserver_1`
4. See the exception

**Expected behavior**
Converting the odt document to PDF.

**Webserver logs**
```
15:19:23 [Q] INFO Process-1:1 processing [test.odt]
[2021-02-13 15:19:23,189] [INFO] [paperless.consumer] Consuming test.odt
[2021-02-13 15:19:23,195] [INFO] [paperless.parsing.tika] Sending /usr/src/paperless/src/../consume/test.odt to Tika server
[2021-02-13 15:19:23,247] [INFO] [paperless.parsing.tika] Converting /usr/src/paperless/src/../consume/test.odt to PDF as /tmp/paperless/paperless-30l71j8v/convert.pdf
[2021-02-13 15:19:33,643] [ERROR] [paperless.consumer] Error while consuming document test.odt: Error while converting document to PDF: 504 Server Error: Gateway Timeout for url: http://gotenberg:3000/convert/office
15:19:33 [Q] ERROR Failed [test.odt] - test.odt: Error while consuming document test.odt: Error while converting document to PDF: 504 Server Error: Gateway Timeout for url: http://gotenberg:3000/convert/office : Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 79, in convert_to_pdf
    response.raise_for_status()  # ensure we notice bad responses
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: http://gotenberg:3000/convert/office

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 208, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 238, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 65, in parse
    self.archive_path = self.convert_to_pdf(document_path, file_name)
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in convert_to_pdf
    f"Error while converting document to PDF: {err}"
documents.parsers.ParseError: Error while converting document to PDF: 504 Server Error: Gateway Timeout for url: http://gotenberg:3000/convert/office

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 82, in consume_file
    task_id=task_id
  File "/usr/src/paperless/src/documents/consumer.py", line 258, in try_consume_file
    f"Error while consuming document {self.filename}: {e}"
  File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: test.odt: Error while consuming document test.odt: Error while converting document to PDF: 504 Server Error: Gateway Timeout for url: http://gotenberg:3000/convert/office
```

**Relevant information**
 - Host OS of the machine running paperless: Archlinux
 - Browser firefox
 - Version 1.1.1
 - Installation method: docker

**Workaround**

```
docker exec -it paperless_webserver_1 /bin/bash
sed -i 's/response.raise_for_status/#response.raise_for_status/' /usr/src/paperless/src/paperless_tika/parsers.py
```

```
15:21:19 [Q] INFO Process-1:2 processing [test.odt]
[2021-02-13 15:21:19,208] [INFO] [paperless.consumer] Consuming test.odt
[2021-02-13 15:21:19,216] [INFO] [paperless.parsing.tika] Sending /usr/src/paperless/src/../consume/test.odt to Tika server
[2021-02-13 15:21:19,263] [INFO] [paperless.parsing.tika] Converting /usr/src/paperless/src/../consume/test.odt to PDF as /tmp/paperless/paperless-yv6g02gj/convert.pdf
/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1370: RuntimeWarning: DateTimeField Document.created received a naive datetime (2021-02-13 14:52:50.218143) while time zone support is active.
  RuntimeWarning)
[2021-02-13 15:21:30,240] [INFO] [paperless.consumer] Document 2021-02-13 test consumption finished
15:21:30 [Q] INFO Processed [test.odt]
```

**Comment by jonaswinkler** [comment]
This error indicates that paperless cannot reach the gotenberg server. This server is responsible for converting office documents into PDF documents. Without doing that, the front end cannot display these documents, which is a major drawback.

I'd verify that this service is actually running (`docker container ls | grep gotenberg`) and if not, start it. In case you're using the docker-compose files (you didn't exactly specify that), `docker-compose down` and `up` will restart your instance and gotenberg along with it.

Your workaround prevents paperless from aborting consumption in case PDF conversion fails. If my logic is correct, you should not be able to view PDF files for "test.odt" in paperless.
