### ISSUE TITLE
[Errno 13] Permission denied: '/usr/src/paperless/src/../media/documents/archive'

### ISSUE THREAD

**Issue by kopfpolster** [jonaswinkler/paperless-ng#753]
hi!
i installed paperless-ng via docker script on my RPi4, and web interface, mail import etc. works just fine!
But processing Documents produces an error: PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../media/documents/archive'

```
[Errno 13] Permission denied: '/usr/src/paperless/src/../media/documents/archive' : 
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])

File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
task_id=task_id

File "/usr/src/paperless/src/documents/consumer.py", line 186, in try_consume_file
self.pre_check_directories()

File "/usr/src/paperless/src/documents/consumer.py", line 106, in pre_check_directories
os.makedirs(settings.ARCHIVE_DIR, exist_ok=True)

File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../media/documents/archive'
```

It seems like an permission problem, so i followed [Troubleshooting](https://paperless-ng.readthedocs.io/en/latest/troubleshooting.html#permission-denied-errors-in-the-consumption-directory)

My User (pi) is USERMAP_UID and USERMAP_GID 1000. 

Is this a problem with docker-compose? Where do i need to change the permissions?
Thank you for bringing paperless back on track!

**Comment by jonaswinkler** [comment]
Post your docker-compose.yml.

**Comment by kopfpolster** [comment]
thank you for your fast answer!

docker-compose.env:
```
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY= (hidden)
```

docker-compose.yml:
```
# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - /media/ablage:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/pi/paperless-ng/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:

```

**Comment by jonaswinkler** [comment]
>       - /media/ablage:/usr/src/paperless/media

Check that you've got the proper permissions to create and modify the folder `/media/ablage/documents/archive`.
