### ISSUE TITLE
[BUG] Paperless does not process PDFs with white / empty pages in between

### ISSUE THREAD

**Issue by fwiessner** [jonaswinkler/paperless-ng#793]
**Describe the bug**
When consuming a PDF of multiple pages with empty pages in between, as it could happen if you duplex-scan documents and some of the back of the pages are empty, paperless-ng does not process the file, but produces an error:

```
[2021-03-19 14:55:47,857] [ERROR] [paperless.parsing.tesseract] Encountered the following error while running OCR, attempting force OCR to get the text.

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 239, in parse

    "No text was found in the original document")

paperless_tesseract.parsers.NoTextFoundException: No text was found in the original document

```

**To Reproduce**
consume PDF with blank pages in between, go to error log

**Expected behavior**
process the PDF anyway and skip pages if OCR does not detect any text.

**Screenshots**

**Webserver logs**
```
[2021-03-19 14:55:47,857] [ERROR] [paperless.parsing.tesseract] Encountered the following error while running OCR, attempting force OCR to get the text.

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 239, in parse

    "No text was found in the original document")
paperless_tesseract.parsers.NoTextFoundException: No text was found in the original document
```

**Relevant information**
```
docker image ls
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
jonaswinkler/paperless-ng    latest              7052732b68a2        22 hours ago        980MB
redis                        6.0                 090314e0c44c        6 days ago          104MB
postgres                     13                  c5ec7353d87d        7 days ago          314MB
thecodingmachine/gotenberg   latest              3fd9a88f1c36        2 months ago        2.1GB
apache/tika                  latest              839dd51d6257        3 months ago        406MB


```

**Comment by jonaswinkler** [comment]
This error message does not indicate a failure yet. When this error is thrown, paperless failed to get any text from your document using your settings, and will attempt to get the text again using different settings. The odds of paperless succeeding with these safe settings are much higher.

Therefore:

* Please confirm that the document is in fact not added to paperless. If so, please post the full log for that document.
* Also provide a sample file, if possible.

**Comment by fwiessner** [comment]
full log: 
```

`[2021-03-19 23:13:24,968] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/CCF13122018_00001.pdf to the task queue.

[2021-03-19 23:13:25,092] [INFO] [paperless.consumer] Consuming CCF13122018_00001.pdf

[2021-03-19 23:13:25,097] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2021-03-19 23:13:25,152] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2021-03-19 23:13:25,160] [DEBUG] [paperless.consumer] Parsing CCF13122018_00001.pdf...

[2021-03-19 23:13:25,792] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/src/../consume/CCF13122018_00001.pdf

[2021-03-19 23:13:25,908] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/CCF13122018_00001.pdf', 'output_file': '/tmp/paperless/paperless-92_3s92v/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-92_3s92v/sidecar.txt'}

[2021-03-19 23:14:08,406] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-92_3s92v

[2021-03-19 23:14:08,417] [ERROR] [paperless.consumer] Error while consuming document CCF13122018_00001.pdf: LeptonicaError: [2021-03-19 23:13:36,038] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.`

How can i debug any further?

```

**Comment by jonaswinkler** [comment]
There's no `NoTextFoundException` in that log, so that seems to be a different document?

**Comment by fwiessner** [comment]
I don't know. How can i debug this and get the error message from tesseract instead of leptonica only printing that there has been an error to get the root-cause? I started a bash inside the paperless-webserver docker instance but don't know what to execute from there to get any debug output

**Comment by jonaswinkler** [comment]
If you could provide some example files that don't get processed properly, that would be great. It's most likely an issue with `OCRmyPDF`, which is the library I use for OCR. I can forward the issue to their repo, but they also need a sample file.

**Comment by fwiessner** [comment]
I cannot give you the files, they contain sensitive informtions and it would be prohibited by DSGVO. Please advice how to debug further.

**Comment by fwiessner** [comment]
i have a file, i could mail to you if you do not disclose it:

[2021-03-22 07:14:33,074] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/CCF16072019.pdf to the task queue.

[2021-03-22 07:14:34,440] [INFO] [paperless.consumer] Consuming CCF16072019.pdf

[2021-03-22 07:14:34,447] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2021-03-22 07:14:34,492] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2021-03-22 07:14:34,497] [DEBUG] [paperless.consumer] Parsing CCF16072019.pdf...

[2021-03-22 07:14:34,860] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/src/../consume/CCF16072019.pdf

[2021-03-22 07:14:35,133] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/CCF16072019.pdf', 'output_file': '/tmp/paperless/paperless-xafuzqar/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-xafuzqar/sidecar.txt'}

[2021-03-22 07:15:07,008] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-xafuzqar

[2021-03-22 07:15:07,017] [ERROR] [paperless.consumer] Error while consuming document CCF16072019.pdf: LeptonicaError: [2021-03-22 07:14:48,044] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
