### ISSUE TITLE
[BUG] Debug Mode breaks start

### ISSUE THREAD

**Issue by Bart1909** [jonaswinkler/paperless-ng#810]
Wanted to start paperless via docker in debug mode.
When I enable 
`PAPERLESS_DEBUG=true`
and start the containers, I got the following error and the container restarts all the time:
`ebserver_1  | 2021-03-23 06:58:44,362 INFO spawned: 'gunicorn' with pid 55
webserver_1  | System check identified some issues:
webserver_1  | 
webserver_1  | WARNINGS:
webserver_1  | ?: DEBUG mode is enabled. Disable Debug mode. This is a serious security issue, since it puts security overides in place which are meant to be only used during development. This also means that paperless will tell anyone various debugging information when something goes wrong.
webserver_1  | 07:58:44 [Q] INFO Q Cluster utah-wisconsin-speaker-winner starting.
webserver_1  | 07:58:44 [Q] INFO Process-1:1 ready for work at 58
webserver_1  | 07:58:44 [Q] INFO Process-1 guarding cluster utah-wisconsin-speaker-winner
webserver_1  | 07:58:44 [Q] INFO Process-1:3 monitoring at 60
webserver_1  | 07:58:44 [Q] INFO Process-1:4 pushing tasks at 61
webserver_1  | 07:58:44 [Q] INFO Q Cluster utah-wisconsin-speaker-winner running.
webserver_1  | 07:58:44 [Q] INFO Process-1:2 ready for work at 59
webserver_1  | [2021-03-23 06:58:44 +0000] [55] [INFO] Starting gunicorn 20.0.4
webserver_1  | [2021-03-23 06:58:45 +0000] [55] [INFO] Listening at: http://0.0.0.0:8000 (55)
webserver_1  | [2021-03-23 06:58:45 +0000] [55] [INFO] Using worker: uvicorn.workers.UvicornWorker
webserver_1  | [2021-03-23 06:58:45 +0000] [55] [INFO] Server is ready. Spawning workers
webserver_1  | [2021-03-23 06:58:45 +0000] [64] [INFO] Booting worker with pid: 64
webserver_1  | [2021-03-23 06:58:45 +0000] [65] [INFO] Booting worker with pid: 65
webserver_1  | 2021-03-23 06:58:45,715 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | [2021-03-23 07:58:45 +0100] [64] [ERROR] Exception in worker process
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
webserver_1  |     worker.init_process()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 63, in init_process
webserver_1  |     super(UvicornWorker, self).init_process()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
webserver_1  |     self.load_wsgi()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
webserver_1  |     self.wsgi = self.app.wsgi()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
webserver_1  |     self.callable = self.load()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
webserver_1  |     return self.load_wsgiapp()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
webserver_1  |     return util.import_app(self.app_uri)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
webserver_1  |     mod = importlib.import_module(module)
webserver_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
webserver_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webserver_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
webserver_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
webserver_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
webserver_1  |   File "/usr/src/paperless/src/paperless/asgi.py", line 9, in <module>
webserver_1  |     django_asgi_app = get_asgi_application()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/asgi.py", line 12, in get_asgi_application
webserver_1  |     django.setup(set_prefix=False)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
webserver_1  |     apps.populate(settings.INSTALLED_APPS)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
webserver_1  |     app_config = AppConfig.create(entry)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
webserver_1  |     mod = import_module(mod_path)
webserver_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
webserver_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webserver_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
webserver_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
webserver_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/channels/apps.py", line 4, in <module>
webserver_1  |     import daphne.server
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/daphne/server.py", line 20, in <module>
webserver_1  |     asyncioreactor.install(twisted_loop)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
webserver_1  |     reactor = AsyncioSelectorReactor(eventloop)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 61, in __init__
webserver_1  |     "SelectorEventLoop required, instead got: {}".format(_eventloop)
webserver_1  | TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
webserver_1  | [2021-03-23 07:58:45 +0100] [64] [INFO] Worker exiting (pid: 64)
webserver_1  | [2021-03-23 07:58:45 +0100] [65] [ERROR] Exception in worker process
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
webserver_1  |     worker.init_process()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 63, in init_process
webserver_1  |     super(UvicornWorker, self).init_process()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
webserver_1  |     self.load_wsgi()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
webserver_1  |     self.wsgi = self.app.wsgi()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
webserver_1  |     self.callable = self.load()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
webserver_1  |     return self.load_wsgiapp()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
webserver_1  |     return util.import_app(self.app_uri)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
webserver_1  |     mod = importlib.import_module(module)
webserver_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
webserver_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webserver_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
webserver_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
webserver_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
webserver_1  |   File "/usr/src/paperless/src/paperless/asgi.py", line 9, in <module>
webserver_1  |     django_asgi_app = get_asgi_application()
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/asgi.py", line 12, in get_asgi_application
webserver_1  |     django.setup(set_prefix=False)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
webserver_1  |     apps.populate(settings.INSTALLED_APPS)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
webserver_1  |     app_config = AppConfig.create(entry)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
webserver_1  |     mod = import_module(mod_path)
webserver_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
webserver_1  |     return _bootstrap._gcd_import(name[level:], package, level)
webserver_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
webserver_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
webserver_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/channels/apps.py", line 4, in <module>
webserver_1  |     import daphne.server
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/daphne/server.py", line 20, in <module>
webserver_1  |     asyncioreactor.install(twisted_loop)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
webserver_1  |     reactor = AsyncioSelectorReactor(eventloop)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 61, in __init__
webserver_1  |     "SelectorEventLoop required, instead got: {}".format(_eventloop)
webserver_1  | TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
webserver_1  | [2021-03-23 07:58:45 +0100] [65] [INFO] Worker exiting (pid: 65)
webserver_1  | [2021-03-23 06:58:45 +0000] [55] [INFO] Shutting down: Master
webserver_1  | [2021-03-23 06:58:45 +0000] [55] [INFO] Reason: Worker failed to boot.
webserver_1  | 2021-03-23 06:58:47,020 INFO exited: gunicorn (exit status 3; not expected)
`

If I disable the debug mode, everything is fine.
I wanted to enable the debug code, to use the backend from the docker environment to have a look at the frontend development and to bypass CORS configuration

**Comment by jonaswinkler** [comment]
Not sure If I can do much about that.

* The issue is that a certain part of paperless needs to be enabled in debug mode, and disabled in production mode. Namely the "channels" django application.

* If that's enabled, it will interfere with the production web server that the docker image uses when DEBUG is enabled.
* It's absolutely required for development.

**Comment by ebardsley** [comment]
Perhaps the right thing to do is to disable channels when run inside gunicorn or docker? Setting environment variable in the Docker entrypoint should make identifying this case straightforward. The development model of "use ng serve to point to a docker backend" is useful, and seems to work acceptably without channels, especially on platforms like Mac, where building all of the dependencies for the backend locally is painful.
