### ISSUE TITLE
[BUG] Document checksum fail on import

### ISSUE THREAD

**Issue by shiner66** [jonaswinkler/paperless-ng#910]
**Describe the bug**
Paperless-ng refusing to consume files due to `UNIQUE constraint failed: documents_document.checksum
`
For clarity purposes regarding #213, the documents are not identical, even though some of them are named similarly, but It doesn't seem to affect how often such behaviour is triggered.

**To Reproduce**
1.Copy various documents in consume folder

**Expected behavior**
Documents being correctly imported.

**Screenshots**
N/A

**Webserver logs**
```
[2021-04-13 19:38:57,489] [ERROR] [paperless.consumer] The following error occured while consuming doc_selladigit_banca.pdf: UNIQUE constraint failed: documents_document.checksum

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: documents_document.checksum


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/src/paperless/src/documents/consumer.py", line 290, in try_consume_file
mime_type=mime_type
File "/usr/src/paperless/src/documents/consumer.py", line 380, in _store
storage_type=storage_type
File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 447, in create
obj.save(force_insert=True, using=self.db)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 754, in save
force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 792, in save_base
force_update, using, update_fields,
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 895, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 935, in _do_insert
using=using, raw=raw,
File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1254, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: documents_document.checksum

19:38:57 [Q] INFO Process-1:32 stopped doing work
19:38:57 [Q] ERROR Failed [doc_selladigit_banca.pdf] - doc_selladigit_banca.pdf: The following error occured while consuming doc_selladigit_banca.pdf: UNIQUE constraint failed: documents_document.checksum : Traceback (most recent call last):

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: documents_document.checksum


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 208, in main_wrap
raise exc_info[1]
File "/usr/src/paperless/src/documents/consumer.py", line 290, in try_consume_file
mime_type=mime_type
File "/usr/src/paperless/src/documents/consumer.py", line 380, in _store
storage_type=storage_type
File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 447, in create
obj.save(force_insert=True, using=self.db)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 754, in save
force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 792, in save_base
force_update, using, update_fields,
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 895, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 935, in _do_insert
using=using, raw=raw,
File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1254, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: documents_document.checksum


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
task_id=task_id
File "/usr/src/paperless/src/documents/consumer.py", line 341, in try_consume_file
exc_info=True
File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: doc_selladigit_banca.pdf: The following error occured while consuming doc_selladigit_banca.pdf: UNIQUE constraint failed: documents_document.checksum
```

**Relevant information**
 - Unraid 6.9.1/Docker 19.03.14
 - Chrome
 - Version 89.0.4389.114
 - Installation method: Docker

**Comment by jonaswinkler** [comment]
That most likely happens when you try to add the same document twice. Either way, this is just another message that the specified document is already in paperless, according to the file checksum.

**Comment by jonaswinkler** [comment]
Two possible cases:

* There are some duplicates within the set of documents you added (Did you add multiple documents at the same time?).
* Highly unlikely: Two of your documents with different content have the same md5 checksum.

**Comment by shiner66** [comment]
I honestly have no clue about what's going on as it's mathematically improbable to have two different files with the same md5 hash, we're talking 2-¹²⁸.

But nevertheless as you said the issue seems to clearly be a hash collision.

I did check and they weren't already present in the database, but it ingested them correctly after a few tries though.

**Comment by jonaswinkler** [comment]
If you've got a multi-core system (at least 4 cores with default settings), you can easily reproduce this error by simply dragging the same file into the upload box or consumption folder twice, at the same time. Paperless will process them in parallel, and one will fail at the end.

This might help you in figuring out what's happening.

**Comment by JeremyMorel** [comment]
Hi There - Wanted to contribute to this thread, since I'm also experiencing the issue.  

My details are:

- I'm running the Docker @version, 1.4.5.  
- I'm mounting the path to my consume folder as a network share to my workstation. 
- I copy a single document from my workstation to the consume share.
- The UI status seems to indicate an attempt to import the single copy of the document two times.  
- My workstation happens to be MacOS Catalina, but this behavior happens on Windows Linux as well.
 
For me, the document does seem finally seem to make it in, and is removed from the consume folder after some time. However the UI continues to process a second import, which fails, presumably because the first task has consumed the document. Sometimes I'll also get an error that the document cannot be found, which seems logical since the fist import task has removed it.  

The screen capture shows what I see when opying a single file into my consume folder.    
 If I delete the imported document from my library, then import it via the Web UI, (Drag and drop or browse), things work normally.

I'm wondering if perhaps the consumer is grabbing the file before it finishes copying, and thus it's triggered again at the finish?  This is just a guess...  
![paperless-ng](https://user-images.githubusercontent.com/16241681/127203773-ca0b6706-b3db-4270-b22d-ee798ce20028.gif)

**Comment by JeremyMorel** [comment]
Some additional info-- I wonder if this may be specific to Docker. [(see here.)](https://ieeexplore.ieee.org/document/9220753) Perhaps I need to see if there's a way to alter behaviors for certain folders or mount Points.

**Comment by JeremyMorel** [comment]
Ok-- so i was onto something with docker being to blame.  [Here's another thread I've been working in parallel with a path toward resolution...](https://github.com/jonaswinkler/paperless-ng/issues/1084#issuecomment-887922748)
