### ISSUE TITLE
[BUG] Django Python error "date value out of range"

### ISSUE THREAD

**Issue by chris42** [jonaswinkler/paperless-ng#927]
**Describe the bug**
Paperless is not able to consume a specific document. Have roughly imported ~1000 other documents successfully. However this single one stops and produces python error. File is 10 page, 1.2MB pdf with table full of numbers and dates.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place file in directory for consumption
2. Wait for it to be picked up by paperless and being analysed
3. Wait a few minutes
4. See error in admin failed django tasks

**Expected behaviour**
Regular consumption of document without error

**logs from admin console**
```
date value out of range : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
task_id=task_id
File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
date = parse_date(self.filename, text)
File "/usr/src/paperless/src/documents/parsers.py", line 260, in parse_date
date = __parser(date_string, settings.DATE_ORDER)
File "/usr/src/paperless/src/documents/parsers.py", line 227, in __parser
True
File "/usr/local/lib/python3.7/site-packages/dateparser/conf.py", line 89, in wrapper
return f(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/dateparser/__init__.py", line 54, in parse
data = parser.get_date_data(date_string, date_formats)
File "/usr/local/lib/python3.7/site-packages/dateparser/date.py", line 422, in get_date_data
locale, date_string, date_formats, settings=self._settings)
File "/usr/local/lib/python3.7/site-packages/dateparser/date.py", line 178, in parse
return instance._parse()
File "/usr/local/lib/python3.7/site-packages/dateparser/date.py", line 182, in _parse
date_data = self._parsers[parser_name]()
File "/usr/local/lib/python3.7/site-packages/dateparser/date.py", line 201, in _try_absolute_parser
return self._try_parser(parse_method=_parse_absolute)
File "/usr/local/lib/python3.7/site-packages/dateparser/date.py", line 213, in _try_parser
self._get_translated_date(), parse_method=parse_method, settings=self._settings)
File "/usr/local/lib/python3.7/site-packages/dateparser/conf.py", line 89, in wrapper
return f(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/dateparser/date_parser.py", line 35, in parse
date_obj = stz.localize(date_obj)
File "/usr/local/lib/python3.7/site-packages/pytz/tzinfo.py", line 323, in localize
loc_dt = dt + delta
OverflowError: date value out of range
```

**Relevant information**
 - Host OS: Debian 10
 - Browser: Firefox 87
 - Version: 1.4.0
 - Installation method: docker
 - Changed docker-compose setup to latest redis, own network setup, added logging driver definition
 - Using following setting in docker-compose.env:
USERMAP_UID, USERMAP_GID, PAPERLESS_SECRET_KEY, PAPERLESS_TIME_ZONE, PAPERLESS_OCR_LANGUAGE, PAPERLESS_FILENAME_FORMAT

**Comment by Burschi500** [comment]
This seems to be the same as #1007

**Comment by jonaswinkler** [comment]
No, it's not.

**Comment by chris42** [comment]
So is there any solution for this or something I can help with to create one?

**Comment by chris42** [comment]
So just tested this on version 1.5.0 and the document is being consumed. Closing
