### ISSUE TITLE
[BUG] KeyError: 'ID' when importing a document

### ISSUE THREAD

**Issue by amuttsch** [jonaswinkler/paperless-ng#939]
**Describe the bug**
When importing a document the import fails with `KeyError: 'ID'`.

**To Reproduce**
Import document and wait :-) Unfortunately, I cannot share the document as it contains sensitive data.
I think the error occurs while OCRing the document.

This issue occurs only on two documents so far. Other files can be imported successfully.

**Expected behavior**
The document is imported successfully.

**Webserver logs**
```

'ID' : Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
task_id=task_id
File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
document_parser.parse(self.path, mime_type, self.filename)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 212, in parse
text_original = self.extract_text(None, document_path)
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 120, in extract_text
stripped = post_process_text(pdfminer_extract_text(pdf_file))
File "/usr/local/lib/python3.7/site-packages/pdfminer/high_level.py", line 119, in extract_text
caching=caching,
File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfpage.py", line 128, in get_pages
doc = PDFDocument(parser, password=password, caching=caching)
File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfdocument.py", line 586, in __init__
self.encryption = (list_value(trailer['ID']),
KeyError: 'ID'
```

**Relevant information**
 - Host OS of the machine running paperless: Raspian 64bit
 - Browser: Firefox
 - Version: Paperless-ng 1.4.1 
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: none

**Comment by jonaswinkler** [comment]
This is an issue of pdfminer (used for extracting text from PDF documents). There's already an open issue for that on their end: https://github.com/pdfminer/pdfminer.six/issues/594.

**Comment by amuttsch** [comment]
Ahh okay, thanks for the hint!

**Comment by amuttsch** [comment]
Thanks for this update with the fix! :-) How did you fix it? The library seems not updated yet. Can you link the commit that fixed the issue - I'm curious :-)
