### ISSUE TITLE
[BUG] error consuming pdf: object of type 'PSKeyword' has no len()

### ISSUE THREAD

**Issue by s-oliver** [jonaswinkler/paperless-ng#981]
**Describe the bug**
I have a set of documents from one correspondent that fail to process all the time:
```
TypeError: object of type 'PSKeyword' has no len()
```

**To Reproduce**
It's reproducible with a set of pdfs I have here. I have used the webinterface to upload them as well as put them in the consumption folder, it makes no difference.

**Expected behavior**
I would expect the pdfs to be processed just like any other document.

**Webserver logs**

```
webserver_1  | 21:17:32 [Q] INFO Enqueued 1
webserver_1  | 21:17:32 [Q] INFO Process-1:122 processing [rechnung_2.pdf]
webserver_1  | [2021-05-03 21:17:32,447] [INFO] [paperless.consumer] Consuming rechnung_2.pdf
webserver_1  | 21:17:32 [Q] INFO Process-1:122 stopped doing work
webserver_1  | 21:17:32 [Q] ERROR Failed [rechnung_2.pdf] - object of type 'PSKeyword' has no len() : Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 81, in consume_file
webserver_1  |     task_id=task_id
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 248, in try_consume_file
webserver_1  |     document_parser.parse(self.path, mime_type, self.filename)
webserver_1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 212, in parse
webserver_1  |     text_original = self.extract_text(None, document_path)
webserver_1  |   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 120, in extract_text
webserver_1  |     stripped = post_process_text(pdfminer_extract_text(pdf_file))
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/high_level.py", line 121, in extract_text
webserver_1  |     interpreter.process_page(page)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
webserver_1  |     self.render_contents(page.resources, page.contents, ctm=ctm)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
webserver_1  |     self.execute(list_value(streams))
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 933, in execute
webserver_1  |     func(*args)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 803, in do_TJ
webserver_1  |     self.graphicstate.copy())
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfdevice.py", line 83, in render_string
webserver_1  |     graphicstate)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfdevice.py", line 96, in render_string_horizontal
webserver_1  |     for cid in font.decode(obj):
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/pdffont.py", line 776, in decode
webserver_1  |     return self.cmap.decode(bytes)
webserver_1  |   File "/usr/local/lib/python3.7/site-packages/pdfminer/cmapdb.py", line 115, in decode
webserver_1  |     n = len(code)//2
webserver_1  | TypeError: object of type 'PSKeyword' has no len()
```

**Relevant information**
 - Host OS of the machine running paperless: Debian 10
 - Version 1.4.1
 - Installation method: docker

**Comment by s-oliver** [comment]
I have updated to 1.4.2, the issue still persists (unexpectedly, seeing the changelog only contains one unrelated issue)

**Comment by jonaswinkler** [comment]
Please post this issue over at https://github.com/pdfminer/pdfminer.six.

The stack trace will be useful to them. They'll probably need an example file as well.

The version of pdfminer.six used in paperless is `20201018`.

**Comment by s-oliver** [comment]
Thanks, with the fix in https://github.com/jonaswinkler/paperless-ng/commit/814d90745b191398802d6d1806fbd4ae198749a8 the documents are indexed. The document content is available as text and the full text search picks up on it.
